//
//Copyright 2026 The BlanketOps Authors.
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//http://www.apache.org/licenses/LICENSE-2.0
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: blanketops/events/v1/githubpayload.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GitHubPayloadService_CreateGitHubPayload_FullMethodName = "/blanketops.events.v1.GitHubPayloadService/CreateGitHubPayload"
	GitHubPayloadService_GetGitHubPayload_FullMethodName    = "/blanketops.events.v1.GitHubPayloadService/GetGitHubPayload"
	GitHubPayloadService_ListGitHubPayloads_FullMethodName  = "/blanketops.events.v1.GitHubPayloadService/ListGitHubPayloads"
	GitHubPayloadService_DeleteGitHubPayload_FullMethodName = "/blanketops.events.v1.GitHubPayloadService/DeleteGitHubPayload"
	GitHubPayloadService_WatchGitHubPayload_FullMethodName  = "/blanketops.events.v1.GitHubPayloadService/WatchGitHubPayload"
)

// GitHubPayloadServiceClient is the client API for GitHubPayloadService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// -----------------------------------------------------------------------------
// Service
// -----------------------------------------------------------------------------
type GitHubPayloadServiceClient interface {
	// ── CRD surface — payloads are immutable, no Update/Patch ───────────────
	// Record a received delivery. Platform-internal ingestion path.
	CreateGitHubPayload(ctx context.Context, in *CreateGitHubPayloadRequest, opts ...grpc.CallOption) (*CreateGitHubPayloadResponse, error)
	// Fetch a GitHubPayload CR by name.
	GetGitHubPayload(ctx context.Context, in *GetGitHubPayloadRequest, opts ...grpc.CallOption) (*GetGitHubPayloadResponse, error)
	// List GitHubPayload CRs with optional repository/phase/type filter and paging.
	ListGitHubPayloads(ctx context.Context, in *ListGitHubPayloadsRequest, opts ...grpc.CallOption) (*ListGitHubPayloadsResponse, error)
	// Delete a GitHubPayload CR. Normally handled by scrub + garbage collection.
	DeleteGitHubPayload(ctx context.Context, in *DeleteGitHubPayloadRequest, opts ...grpc.CallOption) (*DeleteGitHubPayloadResponse, error)
	// ── Streaming ────────────────────────────────────────────────────────────
	// Stream state transitions for GitHubPayload CRs by name or label selector.
	WatchGitHubPayload(ctx context.Context, in *WatchGitHubPayloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchGitHubPayloadResponse], error)
}

type gitHubPayloadServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGitHubPayloadServiceClient(cc grpc.ClientConnInterface) GitHubPayloadServiceClient {
	return &gitHubPayloadServiceClient{cc}
}

func (c *gitHubPayloadServiceClient) CreateGitHubPayload(ctx context.Context, in *CreateGitHubPayloadRequest, opts ...grpc.CallOption) (*CreateGitHubPayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGitHubPayloadResponse)
	err := c.cc.Invoke(ctx, GitHubPayloadService_CreateGitHubPayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubPayloadServiceClient) GetGitHubPayload(ctx context.Context, in *GetGitHubPayloadRequest, opts ...grpc.CallOption) (*GetGitHubPayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGitHubPayloadResponse)
	err := c.cc.Invoke(ctx, GitHubPayloadService_GetGitHubPayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubPayloadServiceClient) ListGitHubPayloads(ctx context.Context, in *ListGitHubPayloadsRequest, opts ...grpc.CallOption) (*ListGitHubPayloadsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListGitHubPayloadsResponse)
	err := c.cc.Invoke(ctx, GitHubPayloadService_ListGitHubPayloads_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubPayloadServiceClient) DeleteGitHubPayload(ctx context.Context, in *DeleteGitHubPayloadRequest, opts ...grpc.CallOption) (*DeleteGitHubPayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteGitHubPayloadResponse)
	err := c.cc.Invoke(ctx, GitHubPayloadService_DeleteGitHubPayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gitHubPayloadServiceClient) WatchGitHubPayload(ctx context.Context, in *WatchGitHubPayloadRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchGitHubPayloadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GitHubPayloadService_ServiceDesc.Streams[0], GitHubPayloadService_WatchGitHubPayload_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchGitHubPayloadRequest, WatchGitHubPayloadResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GitHubPayloadService_WatchGitHubPayloadClient = grpc.ServerStreamingClient[WatchGitHubPayloadResponse]

// GitHubPayloadServiceServer is the server API for GitHubPayloadService service.
// All implementations must embed UnimplementedGitHubPayloadServiceServer
// for forward compatibility.
//
// -----------------------------------------------------------------------------
// Service
// -----------------------------------------------------------------------------
type GitHubPayloadServiceServer interface {
	// ── CRD surface — payloads are immutable, no Update/Patch ───────────────
	// Record a received delivery. Platform-internal ingestion path.
	CreateGitHubPayload(context.Context, *CreateGitHubPayloadRequest) (*CreateGitHubPayloadResponse, error)
	// Fetch a GitHubPayload CR by name.
	GetGitHubPayload(context.Context, *GetGitHubPayloadRequest) (*GetGitHubPayloadResponse, error)
	// List GitHubPayload CRs with optional repository/phase/type filter and paging.
	ListGitHubPayloads(context.Context, *ListGitHubPayloadsRequest) (*ListGitHubPayloadsResponse, error)
	// Delete a GitHubPayload CR. Normally handled by scrub + garbage collection.
	DeleteGitHubPayload(context.Context, *DeleteGitHubPayloadRequest) (*DeleteGitHubPayloadResponse, error)
	// ── Streaming ────────────────────────────────────────────────────────────
	// Stream state transitions for GitHubPayload CRs by name or label selector.
	WatchGitHubPayload(*WatchGitHubPayloadRequest, grpc.ServerStreamingServer[WatchGitHubPayloadResponse]) error
	mustEmbedUnimplementedGitHubPayloadServiceServer()
}

// UnimplementedGitHubPayloadServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGitHubPayloadServiceServer struct{}

func (UnimplementedGitHubPayloadServiceServer) CreateGitHubPayload(context.Context, *CreateGitHubPayloadRequest) (*CreateGitHubPayloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateGitHubPayload not implemented")
}
func (UnimplementedGitHubPayloadServiceServer) GetGitHubPayload(context.Context, *GetGitHubPayloadRequest) (*GetGitHubPayloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGitHubPayload not implemented")
}
func (UnimplementedGitHubPayloadServiceServer) ListGitHubPayloads(context.Context, *ListGitHubPayloadsRequest) (*ListGitHubPayloadsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListGitHubPayloads not implemented")
}
func (UnimplementedGitHubPayloadServiceServer) DeleteGitHubPayload(context.Context, *DeleteGitHubPayloadRequest) (*DeleteGitHubPayloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteGitHubPayload not implemented")
}
func (UnimplementedGitHubPayloadServiceServer) WatchGitHubPayload(*WatchGitHubPayloadRequest, grpc.ServerStreamingServer[WatchGitHubPayloadResponse]) error {
	return status.Errorf(codes.Unimplemented, "method WatchGitHubPayload not implemented")
}
func (UnimplementedGitHubPayloadServiceServer) mustEmbedUnimplementedGitHubPayloadServiceServer() {}
func (UnimplementedGitHubPayloadServiceServer) testEmbeddedByValue()                              {}

// UnsafeGitHubPayloadServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GitHubPayloadServiceServer will
// result in compilation errors.
type UnsafeGitHubPayloadServiceServer interface {
	mustEmbedUnimplementedGitHubPayloadServiceServer()
}

func RegisterGitHubPayloadServiceServer(s grpc.ServiceRegistrar, srv GitHubPayloadServiceServer) {
	// If the following call pancis, it indicates UnimplementedGitHubPayloadServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GitHubPayloadService_ServiceDesc, srv)
}

func _GitHubPayloadService_CreateGitHubPayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGitHubPayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubPayloadServiceServer).CreateGitHubPayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubPayloadService_CreateGitHubPayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubPayloadServiceServer).CreateGitHubPayload(ctx, req.(*CreateGitHubPayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubPayloadService_GetGitHubPayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGitHubPayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubPayloadServiceServer).GetGitHubPayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubPayloadService_GetGitHubPayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubPayloadServiceServer).GetGitHubPayload(ctx, req.(*GetGitHubPayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubPayloadService_ListGitHubPayloads_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListGitHubPayloadsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubPayloadServiceServer).ListGitHubPayloads(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubPayloadService_ListGitHubPayloads_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubPayloadServiceServer).ListGitHubPayloads(ctx, req.(*ListGitHubPayloadsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubPayloadService_DeleteGitHubPayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteGitHubPayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GitHubPayloadServiceServer).DeleteGitHubPayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GitHubPayloadService_DeleteGitHubPayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GitHubPayloadServiceServer).DeleteGitHubPayload(ctx, req.(*DeleteGitHubPayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GitHubPayloadService_WatchGitHubPayload_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchGitHubPayloadRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GitHubPayloadServiceServer).WatchGitHubPayload(m, &grpc.GenericServerStream[WatchGitHubPayloadRequest, WatchGitHubPayloadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GitHubPayloadService_WatchGitHubPayloadServer = grpc.ServerStreamingServer[WatchGitHubPayloadResponse]

// GitHubPayloadService_ServiceDesc is the grpc.ServiceDesc for GitHubPayloadService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GitHubPayloadService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "blanketops.events.v1.GitHubPayloadService",
	HandlerType: (*GitHubPayloadServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateGitHubPayload",
			Handler:    _GitHubPayloadService_CreateGitHubPayload_Handler,
		},
		{
			MethodName: "GetGitHubPayload",
			Handler:    _GitHubPayloadService_GetGitHubPayload_Handler,
		},
		{
			MethodName: "ListGitHubPayloads",
			Handler:    _GitHubPayloadService_ListGitHubPayloads_Handler,
		},
		{
			MethodName: "DeleteGitHubPayload",
			Handler:    _GitHubPayloadService_DeleteGitHubPayload_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchGitHubPayload",
			Handler:       _GitHubPayloadService_WatchGitHubPayload_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "blanketops/events/v1/githubpayload.proto",
}
