// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: blanketops/networks/v1/route.proto

package v1

import (
	v1 "github.com/ntlaletsi70/blanketops-environments-contract/blanketops/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Route struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Standard BlanketOps metadata (name, namespace, labels, ownerRef).
	Metadata *v1.Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Desired state declared by the operator.
	Spec *RouteSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	// Observed state set by the controller. Never manually edited.
	Status        *RouteStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1_route_proto_rawDescGZIP(), []int{0}
}

func (x *Route) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Route) GetSpec() *RouteSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Route) GetStatus() *RouteStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type RouteSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fully qualified domain name to serve.
	// e.g. app.dev.blanketops.online
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// Whether the route is active.
	// Disabled routes are removed from the runtime but the CR is retained.
	Enabled bool `protobuf:"varint,2,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// HTTP path prefix to match.
	// e.g. /, /v1, /api
	Path string `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	// Whether TLS is required for this route.
	// Certificate provisioning is delegated to cert-manager via the
	// platform issuer (DNS01 wildcard or namespaced HTTP01).
	TlsEnabled bool `protobuf:"varint,4,opt,name=tls_enabled,json=tlsEnabled,proto3" json:"tls_enabled,omitempty"`
	// Runtime responsible for materializing this route.
	Runtime       *v1.RouteRuntime `protobuf:"bytes,5,opt,name=runtime,proto3" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteSpec) Reset() {
	*x = RouteSpec{}
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteSpec) ProtoMessage() {}

func (x *RouteSpec) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteSpec.ProtoReflect.Descriptor instead.
func (*RouteSpec) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1_route_proto_rawDescGZIP(), []int{1}
}

func (x *RouteSpec) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RouteSpec) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *RouteSpec) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RouteSpec) GetTlsEnabled() bool {
	if x != nil {
		return x.TlsEnabled
	}
	return false
}

func (x *RouteSpec) GetRuntime() *v1.RouteRuntime {
	if x != nil {
		return x.Runtime
	}
	return nil
}

type RouteStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current lifecycle phase. Set by the controller.
	Phase *v1.RoutePhase `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	// Human-readable status message. Populated on failure.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// Resolved address or endpoint once materialized.
	// e.g. load balancer hostname or serving URL.
	ResolvedAddress string `protobuf:"bytes,3,opt,name=resolved_address,json=resolvedAddress,proto3" json:"resolved_address,omitempty"`
	// TLS provisioning status. Set by the controller.
	TlsStatus *v1.RouteTLSStatus `protobuf:"bytes,4,opt,name=tls_status,json=tlsStatus,proto3" json:"tls_status,omitempty"`
	// Conditions for UI and automation consumers.
	Conditions []*RouteCondition `protobuf:"bytes,5,rep,name=conditions,proto3" json:"conditions,omitempty"`
	// When the controller last updated this status.
	LastUpdatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_updated_at,json=lastUpdatedAt,proto3" json:"last_updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RouteStatus) Reset() {
	*x = RouteStatus{}
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteStatus) ProtoMessage() {}

func (x *RouteStatus) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteStatus.ProtoReflect.Descriptor instead.
func (*RouteStatus) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1_route_proto_rawDescGZIP(), []int{2}
}

func (x *RouteStatus) GetPhase() *v1.RoutePhase {
	if x != nil {
		return x.Phase
	}
	return nil
}

func (x *RouteStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RouteStatus) GetResolvedAddress() string {
	if x != nil {
		return x.ResolvedAddress
	}
	return ""
}

func (x *RouteStatus) GetTlsStatus() *v1.RouteTLSStatus {
	if x != nil {
		return x.TlsStatus
	}
	return nil
}

func (x *RouteStatus) GetConditions() []*RouteCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *RouteStatus) GetLastUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdatedAt
	}
	return nil
}

type RouteCondition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Condition type. e.g. RouteResolved, TLSReady, RuntimeReady
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Condition status: True, False, or Unknown.
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Machine-readable reason for the last transition.
	Reason string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	// Human-readable detail for the last transition.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// When the condition last changed status.
	LastTransitionTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=last_transition_time,json=lastTransitionTime,proto3" json:"last_transition_time,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RouteCondition) Reset() {
	*x = RouteCondition{}
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RouteCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouteCondition) ProtoMessage() {}

func (x *RouteCondition) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouteCondition.ProtoReflect.Descriptor instead.
func (*RouteCondition) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1_route_proto_rawDescGZIP(), []int{3}
}

func (x *RouteCondition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RouteCondition) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RouteCondition) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *RouteCondition) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RouteCondition) GetLastTransitionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTransitionTime
	}
	return nil
}

// CreateRoute — declare a new Route intent.
// Controller materializes the runtime resource on reconciliation.
type CreateRouteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Desired spec for the new Route.
	Spec          *RouteSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRouteRequest) Reset() {
	*x = CreateRouteRequest{}
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouteRequest) ProtoMessage() {}

func (x *CreateRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouteRequest.ProtoReflect.Descriptor instead.
func (*CreateRouteRequest) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1_route_proto_rawDescGZIP(), []int{4}
}

func (x *CreateRouteRequest) GetSpec() *RouteSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CreateRouteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created Route including generated metadata and initial status.
	Route         *Route `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRouteResponse) Reset() {
	*x = CreateRouteResponse{}
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRouteResponse) ProtoMessage() {}

func (x *CreateRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRouteResponse.ProtoReflect.Descriptor instead.
func (*CreateRouteResponse) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1_route_proto_rawDescGZIP(), []int{5}
}

func (x *CreateRouteResponse) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

// GetRoute — fetch a Route by name.
type GetRouteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the Route CR to fetch.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteRequest) Reset() {
	*x = GetRouteRequest{}
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteRequest) ProtoMessage() {}

func (x *GetRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteRequest.ProtoReflect.Descriptor instead.
func (*GetRouteRequest) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1_route_proto_rawDescGZIP(), []int{6}
}

func (x *GetRouteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetRouteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Route         *Route                 `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRouteResponse) Reset() {
	*x = GetRouteResponse{}
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRouteResponse) ProtoMessage() {}

func (x *GetRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRouteResponse.ProtoReflect.Descriptor instead.
func (*GetRouteResponse) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1_route_proto_rawDescGZIP(), []int{7}
}

func (x *GetRouteResponse) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

// UpdateRoute — full replace of the Route spec.
// Equivalent to kubectl apply — all fields replaced.
type UpdateRouteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full Route object including metadata and desired spec.
	Route         *Route `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRouteRequest) Reset() {
	*x = UpdateRouteRequest{}
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRouteRequest) ProtoMessage() {}

func (x *UpdateRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRouteRequest.ProtoReflect.Descriptor instead.
func (*UpdateRouteRequest) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1_route_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRouteRequest) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

type UpdateRouteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated Route as observed by the controller.
	Route         *Route `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRouteResponse) Reset() {
	*x = UpdateRouteResponse{}
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRouteResponse) ProtoMessage() {}

func (x *UpdateRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRouteResponse.ProtoReflect.Descriptor instead.
func (*UpdateRouteResponse) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1_route_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateRouteResponse) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

// PatchRoute — partial update using JSON merge patch RFC 7396.
// Only specified fields are updated — others left unchanged.
type PatchRouteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the Route CR to patch.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// JSON merge patch document — RFC 7396.
	// e.g. {"spec":{"enabled":false}}
	Patch         string `protobuf:"bytes,2,opt,name=patch,proto3" json:"patch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchRouteRequest) Reset() {
	*x = PatchRouteRequest{}
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchRouteRequest) ProtoMessage() {}

func (x *PatchRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchRouteRequest.ProtoReflect.Descriptor instead.
func (*PatchRouteRequest) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1_route_proto_rawDescGZIP(), []int{10}
}

func (x *PatchRouteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PatchRouteRequest) GetPatch() string {
	if x != nil {
		return x.Patch
	}
	return ""
}

type PatchRouteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The patched Route as observed by the controller.
	Route         *Route `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchRouteResponse) Reset() {
	*x = PatchRouteResponse{}
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchRouteResponse) ProtoMessage() {}

func (x *PatchRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchRouteResponse.ProtoReflect.Descriptor instead.
func (*PatchRouteResponse) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1_route_proto_rawDescGZIP(), []int{11}
}

func (x *PatchRouteResponse) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

// ListRoutes — list Route CRs with optional filtering and paging.
type ListRoutesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by current lifecycle phase.
	Phase *v1.RoutePhase `protobuf:"bytes,1,opt,name=phase,proto3,oneof" json:"phase,omitempty"`
	// Filter by materializing runtime.
	Runtime *v1.RouteRuntime `protobuf:"bytes,2,opt,name=runtime,proto3,oneof" json:"runtime,omitempty"`
	// Filter by host FQDN.
	Host *string `protobuf:"bytes,3,opt,name=host,proto3,oneof" json:"host,omitempty"`
	// Maximum number of results to return. Server may return fewer.
	PageSize *int32 `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// Token from a previous ListRoutesResponse.next_page_token.
	// Omit for the first request.
	PageToken     *string `protobuf:"bytes,5,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesRequest) Reset() {
	*x = ListRoutesRequest{}
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesRequest) ProtoMessage() {}

func (x *ListRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesRequest.ProtoReflect.Descriptor instead.
func (*ListRoutesRequest) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1_route_proto_rawDescGZIP(), []int{12}
}

func (x *ListRoutesRequest) GetPhase() *v1.RoutePhase {
	if x != nil {
		return x.Phase
	}
	return nil
}

func (x *ListRoutesRequest) GetRuntime() *v1.RouteRuntime {
	if x != nil {
		return x.Runtime
	}
	return nil
}

func (x *ListRoutesRequest) GetHost() string {
	if x != nil && x.Host != nil {
		return *x.Host
	}
	return ""
}

func (x *ListRoutesRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListRoutesRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListRoutesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of Route CRs matching the request filters.
	Routes []*Route `protobuf:"bytes,1,rep,name=routes,proto3" json:"routes,omitempty"`
	// Token to retrieve the next page. Empty if no more results.
	NextPageToken *string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRoutesResponse) Reset() {
	*x = ListRoutesResponse{}
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRoutesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRoutesResponse) ProtoMessage() {}

func (x *ListRoutesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRoutesResponse.ProtoReflect.Descriptor instead.
func (*ListRoutesResponse) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1_route_proto_rawDescGZIP(), []int{13}
}

func (x *ListRoutesResponse) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *ListRoutesResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

// DeleteRoute — delete a Route CR.
// The controller garbage-collects the materialized runtime resource
// and any TLS certificates owned by this route.
type DeleteRouteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the Route CR to delete.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRouteRequest) Reset() {
	*x = DeleteRouteRequest{}
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRouteRequest) ProtoMessage() {}

func (x *DeleteRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRouteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRouteRequest) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1_route_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteRouteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteRouteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the Route was successfully deleted.
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRouteResponse) Reset() {
	*x = DeleteRouteResponse{}
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRouteResponse) ProtoMessage() {}

func (x *DeleteRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRouteResponse.ProtoReflect.Descriptor instead.
func (*DeleteRouteResponse) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1_route_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteRouteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// WatchRoute — stream phase transitions for a Route CR.
// Delivers an event for every controller reconciliation loop.
type WatchRouteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the Route CR to watch.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRouteRequest) Reset() {
	*x = WatchRouteRequest{}
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRouteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRouteRequest) ProtoMessage() {}

func (x *WatchRouteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRouteRequest.ProtoReflect.Descriptor instead.
func (*WatchRouteRequest) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1_route_proto_rawDescGZIP(), []int{16}
}

func (x *WatchRouteRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WatchRouteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current state of the Route at this point in the stream.
	Route *Route `protobuf:"bytes,1,opt,name=route,proto3" json:"route,omitempty"`
	// The type of change that triggered this event.
	Type          v1.EventType `protobuf:"varint,2,opt,name=type,proto3,enum=blanketops.common.v1.EventType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRouteResponse) Reset() {
	*x = WatchRouteResponse{}
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRouteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRouteResponse) ProtoMessage() {}

func (x *WatchRouteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1_route_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRouteResponse.ProtoReflect.Descriptor instead.
func (*WatchRouteResponse) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1_route_proto_rawDescGZIP(), []int{17}
}

func (x *WatchRouteResponse) GetRoute() *Route {
	if x != nil {
		return x.Route
	}
	return nil
}

func (x *WatchRouteResponse) GetType() v1.EventType {
	if x != nil {
		return x.Type
	}
	return v1.EventType(0)
}

var File_blanketops_networks_v1_route_proto protoreflect.FileDescriptor

const file_blanketops_networks_v1_route_proto_rawDesc = "" +
	"\n" +
	"\"blanketops/networks/v1/route.proto\x12\x16blanketops.networks.v1\x1a blanketops/common/v1/event.proto\x1a#blanketops/common/v1/metadata.proto\x1a blanketops/common/v1/route.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x01\n" +
	"\x05Route\x12:\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1e.blanketops.common.v1.MetadataR\bmetadata\x125\n" +
	"\x04spec\x18\x02 \x01(\v2!.blanketops.networks.v1.RouteSpecR\x04spec\x12;\n" +
	"\x06status\x18\x03 \x01(\v2#.blanketops.networks.v1.RouteStatusR\x06status\"\xac\x01\n" +
	"\tRouteSpec\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12\x12\n" +
	"\x04path\x18\x03 \x01(\tR\x04path\x12\x1f\n" +
	"\vtls_enabled\x18\x04 \x01(\bR\n" +
	"tlsEnabled\x12<\n" +
	"\aruntime\x18\x05 \x01(\v2\".blanketops.common.v1.RouteRuntimeR\aruntime\"\xdb\x02\n" +
	"\vRouteStatus\x126\n" +
	"\x05phase\x18\x01 \x01(\v2 .blanketops.common.v1.RoutePhaseR\x05phase\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12)\n" +
	"\x10resolved_address\x18\x03 \x01(\tR\x0fresolvedAddress\x12C\n" +
	"\n" +
	"tls_status\x18\x04 \x01(\v2$.blanketops.common.v1.RouteTLSStatusR\ttlsStatus\x12F\n" +
	"\n" +
	"conditions\x18\x05 \x03(\v2&.blanketops.networks.v1.RouteConditionR\n" +
	"conditions\x12B\n" +
	"\x0flast_updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rlastUpdatedAt\"\xbc\x01\n" +
	"\x0eRouteCondition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12L\n" +
	"\x14last_transition_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x12lastTransitionTime\"K\n" +
	"\x12CreateRouteRequest\x125\n" +
	"\x04spec\x18\x01 \x01(\v2!.blanketops.networks.v1.RouteSpecR\x04spec\"J\n" +
	"\x13CreateRouteResponse\x123\n" +
	"\x05route\x18\x01 \x01(\v2\x1d.blanketops.networks.v1.RouteR\x05route\"%\n" +
	"\x0fGetRouteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"G\n" +
	"\x10GetRouteResponse\x123\n" +
	"\x05route\x18\x01 \x01(\v2\x1d.blanketops.networks.v1.RouteR\x05route\"I\n" +
	"\x12UpdateRouteRequest\x123\n" +
	"\x05route\x18\x01 \x01(\v2\x1d.blanketops.networks.v1.RouteR\x05route\"J\n" +
	"\x13UpdateRouteResponse\x123\n" +
	"\x05route\x18\x01 \x01(\v2\x1d.blanketops.networks.v1.RouteR\x05route\"=\n" +
	"\x11PatchRouteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05patch\x18\x02 \x01(\tR\x05patch\"I\n" +
	"\x12PatchRouteResponse\x123\n" +
	"\x05route\x18\x01 \x01(\v2\x1d.blanketops.networks.v1.RouteR\x05route\"\xae\x02\n" +
	"\x11ListRoutesRequest\x12;\n" +
	"\x05phase\x18\x01 \x01(\v2 .blanketops.common.v1.RoutePhaseH\x00R\x05phase\x88\x01\x01\x12A\n" +
	"\aruntime\x18\x02 \x01(\v2\".blanketops.common.v1.RouteRuntimeH\x01R\aruntime\x88\x01\x01\x12\x17\n" +
	"\x04host\x18\x03 \x01(\tH\x02R\x04host\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x04 \x01(\x05H\x03R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x05 \x01(\tH\x04R\tpageToken\x88\x01\x01B\b\n" +
	"\x06_phaseB\n" +
	"\n" +
	"\b_runtimeB\a\n" +
	"\x05_hostB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\x8c\x01\n" +
	"\x12ListRoutesResponse\x125\n" +
	"\x06routes\x18\x01 \x03(\v2\x1d.blanketops.networks.v1.RouteR\x06routes\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tH\x00R\rnextPageToken\x88\x01\x01B\x12\n" +
	"\x10_next_page_token\"(\n" +
	"\x12DeleteRouteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x13DeleteRouteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"'\n" +
	"\x11WatchRouteRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"~\n" +
	"\x12WatchRouteResponse\x123\n" +
	"\x05route\x18\x01 \x01(\v2\x1d.blanketops.networks.v1.RouteR\x05route\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.blanketops.common.v1.EventTypeR\x04type2\xd6\x05\n" +
	"\fRouteService\x12f\n" +
	"\vCreateRoute\x12*.blanketops.networks.v1.CreateRouteRequest\x1a+.blanketops.networks.v1.CreateRouteResponse\x12]\n" +
	"\bGetRoute\x12'.blanketops.networks.v1.GetRouteRequest\x1a(.blanketops.networks.v1.GetRouteResponse\x12f\n" +
	"\vUpdateRoute\x12*.blanketops.networks.v1.UpdateRouteRequest\x1a+.blanketops.networks.v1.UpdateRouteResponse\x12c\n" +
	"\n" +
	"PatchRoute\x12).blanketops.networks.v1.PatchRouteRequest\x1a*.blanketops.networks.v1.PatchRouteResponse\x12c\n" +
	"\n" +
	"ListRoutes\x12).blanketops.networks.v1.ListRoutesRequest\x1a*.blanketops.networks.v1.ListRoutesResponse\x12f\n" +
	"\vDeleteRoute\x12*.blanketops.networks.v1.DeleteRouteRequest\x1a+.blanketops.networks.v1.DeleteRouteResponse\x12e\n" +
	"\n" +
	"WatchRoute\x12).blanketops.networks.v1.WatchRouteRequest\x1a*.blanketops.networks.v1.WatchRouteResponse0\x01B\x90\x01\n" +
	"\x16v1.networks.blanketopsB\n" +
	"RouteProtoZQgithub.com/ntlaletsi70/blanketops-environments-contract/blanketops/networks/v1;v1\xaa\x02\x16BlanketOps.Networks.V1b\x06proto3"

var (
	file_blanketops_networks_v1_route_proto_rawDescOnce sync.Once
	file_blanketops_networks_v1_route_proto_rawDescData []byte
)

func file_blanketops_networks_v1_route_proto_rawDescGZIP() []byte {
	file_blanketops_networks_v1_route_proto_rawDescOnce.Do(func() {
		file_blanketops_networks_v1_route_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blanketops_networks_v1_route_proto_rawDesc), len(file_blanketops_networks_v1_route_proto_rawDesc)))
	})
	return file_blanketops_networks_v1_route_proto_rawDescData
}

var file_blanketops_networks_v1_route_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_blanketops_networks_v1_route_proto_goTypes = []any{
	(*Route)(nil),                 // 0: blanketops.networks.v1.Route
	(*RouteSpec)(nil),             // 1: blanketops.networks.v1.RouteSpec
	(*RouteStatus)(nil),           // 2: blanketops.networks.v1.RouteStatus
	(*RouteCondition)(nil),        // 3: blanketops.networks.v1.RouteCondition
	(*CreateRouteRequest)(nil),    // 4: blanketops.networks.v1.CreateRouteRequest
	(*CreateRouteResponse)(nil),   // 5: blanketops.networks.v1.CreateRouteResponse
	(*GetRouteRequest)(nil),       // 6: blanketops.networks.v1.GetRouteRequest
	(*GetRouteResponse)(nil),      // 7: blanketops.networks.v1.GetRouteResponse
	(*UpdateRouteRequest)(nil),    // 8: blanketops.networks.v1.UpdateRouteRequest
	(*UpdateRouteResponse)(nil),   // 9: blanketops.networks.v1.UpdateRouteResponse
	(*PatchRouteRequest)(nil),     // 10: blanketops.networks.v1.PatchRouteRequest
	(*PatchRouteResponse)(nil),    // 11: blanketops.networks.v1.PatchRouteResponse
	(*ListRoutesRequest)(nil),     // 12: blanketops.networks.v1.ListRoutesRequest
	(*ListRoutesResponse)(nil),    // 13: blanketops.networks.v1.ListRoutesResponse
	(*DeleteRouteRequest)(nil),    // 14: blanketops.networks.v1.DeleteRouteRequest
	(*DeleteRouteResponse)(nil),   // 15: blanketops.networks.v1.DeleteRouteResponse
	(*WatchRouteRequest)(nil),     // 16: blanketops.networks.v1.WatchRouteRequest
	(*WatchRouteResponse)(nil),    // 17: blanketops.networks.v1.WatchRouteResponse
	(*v1.Metadata)(nil),           // 18: blanketops.common.v1.Metadata
	(*v1.RouteRuntime)(nil),       // 19: blanketops.common.v1.RouteRuntime
	(*v1.RoutePhase)(nil),         // 20: blanketops.common.v1.RoutePhase
	(*v1.RouteTLSStatus)(nil),     // 21: blanketops.common.v1.RouteTLSStatus
	(*timestamppb.Timestamp)(nil), // 22: google.protobuf.Timestamp
	(v1.EventType)(0),             // 23: blanketops.common.v1.EventType
}
var file_blanketops_networks_v1_route_proto_depIdxs = []int32{
	18, // 0: blanketops.networks.v1.Route.metadata:type_name -> blanketops.common.v1.Metadata
	1,  // 1: blanketops.networks.v1.Route.spec:type_name -> blanketops.networks.v1.RouteSpec
	2,  // 2: blanketops.networks.v1.Route.status:type_name -> blanketops.networks.v1.RouteStatus
	19, // 3: blanketops.networks.v1.RouteSpec.runtime:type_name -> blanketops.common.v1.RouteRuntime
	20, // 4: blanketops.networks.v1.RouteStatus.phase:type_name -> blanketops.common.v1.RoutePhase
	21, // 5: blanketops.networks.v1.RouteStatus.tls_status:type_name -> blanketops.common.v1.RouteTLSStatus
	3,  // 6: blanketops.networks.v1.RouteStatus.conditions:type_name -> blanketops.networks.v1.RouteCondition
	22, // 7: blanketops.networks.v1.RouteStatus.last_updated_at:type_name -> google.protobuf.Timestamp
	22, // 8: blanketops.networks.v1.RouteCondition.last_transition_time:type_name -> google.protobuf.Timestamp
	1,  // 9: blanketops.networks.v1.CreateRouteRequest.spec:type_name -> blanketops.networks.v1.RouteSpec
	0,  // 10: blanketops.networks.v1.CreateRouteResponse.route:type_name -> blanketops.networks.v1.Route
	0,  // 11: blanketops.networks.v1.GetRouteResponse.route:type_name -> blanketops.networks.v1.Route
	0,  // 12: blanketops.networks.v1.UpdateRouteRequest.route:type_name -> blanketops.networks.v1.Route
	0,  // 13: blanketops.networks.v1.UpdateRouteResponse.route:type_name -> blanketops.networks.v1.Route
	0,  // 14: blanketops.networks.v1.PatchRouteResponse.route:type_name -> blanketops.networks.v1.Route
	20, // 15: blanketops.networks.v1.ListRoutesRequest.phase:type_name -> blanketops.common.v1.RoutePhase
	19, // 16: blanketops.networks.v1.ListRoutesRequest.runtime:type_name -> blanketops.common.v1.RouteRuntime
	0,  // 17: blanketops.networks.v1.ListRoutesResponse.routes:type_name -> blanketops.networks.v1.Route
	0,  // 18: blanketops.networks.v1.WatchRouteResponse.route:type_name -> blanketops.networks.v1.Route
	23, // 19: blanketops.networks.v1.WatchRouteResponse.type:type_name -> blanketops.common.v1.EventType
	4,  // 20: blanketops.networks.v1.RouteService.CreateRoute:input_type -> blanketops.networks.v1.CreateRouteRequest
	6,  // 21: blanketops.networks.v1.RouteService.GetRoute:input_type -> blanketops.networks.v1.GetRouteRequest
	8,  // 22: blanketops.networks.v1.RouteService.UpdateRoute:input_type -> blanketops.networks.v1.UpdateRouteRequest
	10, // 23: blanketops.networks.v1.RouteService.PatchRoute:input_type -> blanketops.networks.v1.PatchRouteRequest
	12, // 24: blanketops.networks.v1.RouteService.ListRoutes:input_type -> blanketops.networks.v1.ListRoutesRequest
	14, // 25: blanketops.networks.v1.RouteService.DeleteRoute:input_type -> blanketops.networks.v1.DeleteRouteRequest
	16, // 26: blanketops.networks.v1.RouteService.WatchRoute:input_type -> blanketops.networks.v1.WatchRouteRequest
	5,  // 27: blanketops.networks.v1.RouteService.CreateRoute:output_type -> blanketops.networks.v1.CreateRouteResponse
	7,  // 28: blanketops.networks.v1.RouteService.GetRoute:output_type -> blanketops.networks.v1.GetRouteResponse
	9,  // 29: blanketops.networks.v1.RouteService.UpdateRoute:output_type -> blanketops.networks.v1.UpdateRouteResponse
	11, // 30: blanketops.networks.v1.RouteService.PatchRoute:output_type -> blanketops.networks.v1.PatchRouteResponse
	13, // 31: blanketops.networks.v1.RouteService.ListRoutes:output_type -> blanketops.networks.v1.ListRoutesResponse
	15, // 32: blanketops.networks.v1.RouteService.DeleteRoute:output_type -> blanketops.networks.v1.DeleteRouteResponse
	17, // 33: blanketops.networks.v1.RouteService.WatchRoute:output_type -> blanketops.networks.v1.WatchRouteResponse
	27, // [27:34] is the sub-list for method output_type
	20, // [20:27] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_blanketops_networks_v1_route_proto_init() }
func file_blanketops_networks_v1_route_proto_init() {
	if File_blanketops_networks_v1_route_proto != nil {
		return
	}
	file_blanketops_networks_v1_route_proto_msgTypes[12].OneofWrappers = []any{}
	file_blanketops_networks_v1_route_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blanketops_networks_v1_route_proto_rawDesc), len(file_blanketops_networks_v1_route_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blanketops_networks_v1_route_proto_goTypes,
		DependencyIndexes: file_blanketops_networks_v1_route_proto_depIdxs,
		MessageInfos:      file_blanketops_networks_v1_route_proto_msgTypes,
	}.Build()
	File_blanketops_networks_v1_route_proto = out.File
	file_blanketops_networks_v1_route_proto_goTypes = nil
	file_blanketops_networks_v1_route_proto_depIdxs = nil
}
