//
//Copyright 2026 The BlanketOps Authors.
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//http://www.apache.org/licenses/LICENSE-2.0
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: blanketops/common/v1/buildtrigger.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BuildTriggerSource_BuildTriggerSource int32

const (
	BuildTriggerSource_BUILD_TRIGGER_SOURCE_UNSPECIFIED BuildTriggerSource_BuildTriggerSource = 0
	// GitHub webhook, via the GitHubEvent pipeline.
	BuildTriggerSource_BUILD_TRIGGER_SOURCE_GITHUB BuildTriggerSource_BuildTriggerSource = 1
	// GitLab webhook (future).
	BuildTriggerSource_BUILD_TRIGGER_SOURCE_GITLAB BuildTriggerSource_BuildTriggerSource = 2
	// Manual dispatch — operator or CI invoking TriggerBuild.
	BuildTriggerSource_BUILD_TRIGGER_SOURCE_MANUAL BuildTriggerSource_BuildTriggerSource = 3
)

// Enum value maps for BuildTriggerSource_BuildTriggerSource.
var (
	BuildTriggerSource_BuildTriggerSource_name = map[int32]string{
		0: "BUILD_TRIGGER_SOURCE_UNSPECIFIED",
		1: "BUILD_TRIGGER_SOURCE_GITHUB",
		2: "BUILD_TRIGGER_SOURCE_GITLAB",
		3: "BUILD_TRIGGER_SOURCE_MANUAL",
	}
	BuildTriggerSource_BuildTriggerSource_value = map[string]int32{
		"BUILD_TRIGGER_SOURCE_UNSPECIFIED": 0,
		"BUILD_TRIGGER_SOURCE_GITHUB":      1,
		"BUILD_TRIGGER_SOURCE_GITLAB":      2,
		"BUILD_TRIGGER_SOURCE_MANUAL":      3,
	}
)

func (x BuildTriggerSource_BuildTriggerSource) Enum() *BuildTriggerSource_BuildTriggerSource {
	p := new(BuildTriggerSource_BuildTriggerSource)
	*p = x
	return p
}

func (x BuildTriggerSource_BuildTriggerSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildTriggerSource_BuildTriggerSource) Descriptor() protoreflect.EnumDescriptor {
	return file_blanketops_common_v1_buildtrigger_proto_enumTypes[0].Descriptor()
}

func (BuildTriggerSource_BuildTriggerSource) Type() protoreflect.EnumType {
	return &file_blanketops_common_v1_buildtrigger_proto_enumTypes[0]
}

func (x BuildTriggerSource_BuildTriggerSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildTriggerSource_BuildTriggerSource.Descriptor instead.
func (BuildTriggerSource_BuildTriggerSource) EnumDescriptor() ([]byte, []int) {
	return file_blanketops_common_v1_buildtrigger_proto_rawDescGZIP(), []int{0, 0}
}

type BuildTriggerType_BuildTriggerType int32

const (
	BuildTriggerType_BUILD_TRIGGER_TYPE_UNSPECIFIED BuildTriggerType_BuildTriggerType = 0
	// A new commit pushed to a repository.
	BuildTriggerType_BUILD_TRIGGER_TYPE_COMMIT BuildTriggerType_BuildTriggerType = 1
	// A pull request opened or updated.
	BuildTriggerType_BUILD_TRIGGER_TYPE_PULL_REQUEST BuildTriggerType_BuildTriggerType = 2
	// A manual trigger, e.g. via kubectl or CI.
	BuildTriggerType_BUILD_TRIGGER_TYPE_MANUAL BuildTriggerType_BuildTriggerType = 3
)

// Enum value maps for BuildTriggerType_BuildTriggerType.
var (
	BuildTriggerType_BuildTriggerType_name = map[int32]string{
		0: "BUILD_TRIGGER_TYPE_UNSPECIFIED",
		1: "BUILD_TRIGGER_TYPE_COMMIT",
		2: "BUILD_TRIGGER_TYPE_PULL_REQUEST",
		3: "BUILD_TRIGGER_TYPE_MANUAL",
	}
	BuildTriggerType_BuildTriggerType_value = map[string]int32{
		"BUILD_TRIGGER_TYPE_UNSPECIFIED":  0,
		"BUILD_TRIGGER_TYPE_COMMIT":       1,
		"BUILD_TRIGGER_TYPE_PULL_REQUEST": 2,
		"BUILD_TRIGGER_TYPE_MANUAL":       3,
	}
)

func (x BuildTriggerType_BuildTriggerType) Enum() *BuildTriggerType_BuildTriggerType {
	p := new(BuildTriggerType_BuildTriggerType)
	*p = x
	return p
}

func (x BuildTriggerType_BuildTriggerType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildTriggerType_BuildTriggerType) Descriptor() protoreflect.EnumDescriptor {
	return file_blanketops_common_v1_buildtrigger_proto_enumTypes[1].Descriptor()
}

func (BuildTriggerType_BuildTriggerType) Type() protoreflect.EnumType {
	return &file_blanketops_common_v1_buildtrigger_proto_enumTypes[1]
}

func (x BuildTriggerType_BuildTriggerType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildTriggerType_BuildTriggerType.Descriptor instead.
func (BuildTriggerType_BuildTriggerType) EnumDescriptor() ([]byte, []int) {
	return file_blanketops_common_v1_buildtrigger_proto_rawDescGZIP(), []int{1, 0}
}

type BuildTriggerStatus_BuildTriggerStatus int32

const (
	BuildTriggerStatus_BUILD_TRIGGER_STATUS_UNSPECIFIED BuildTriggerStatus_BuildTriggerStatus = 0
	// Trigger has been created but not yet evaluated by the controller.
	BuildTriggerStatus_BUILD_TRIGGER_STATUS_PENDING BuildTriggerStatus_BuildTriggerStatus = 1
	// Controller has accepted the trigger and fired a BuildRun.
	BuildTriggerStatus_BUILD_TRIGGER_STATUS_ACCEPTED BuildTriggerStatus_BuildTriggerStatus = 2
	// Controller has rejected the trigger based on policy or duplication.
	BuildTriggerStatus_BUILD_TRIGGER_STATUS_REJECTED BuildTriggerStatus_BuildTriggerStatus = 3
	// BuildRun has completed; trigger is consumed and awaiting deletion.
	BuildTriggerStatus_BUILD_TRIGGER_STATUS_CONSUMED BuildTriggerStatus_BuildTriggerStatus = 4
)

// Enum value maps for BuildTriggerStatus_BuildTriggerStatus.
var (
	BuildTriggerStatus_BuildTriggerStatus_name = map[int32]string{
		0: "BUILD_TRIGGER_STATUS_UNSPECIFIED",
		1: "BUILD_TRIGGER_STATUS_PENDING",
		2: "BUILD_TRIGGER_STATUS_ACCEPTED",
		3: "BUILD_TRIGGER_STATUS_REJECTED",
		4: "BUILD_TRIGGER_STATUS_CONSUMED",
	}
	BuildTriggerStatus_BuildTriggerStatus_value = map[string]int32{
		"BUILD_TRIGGER_STATUS_UNSPECIFIED": 0,
		"BUILD_TRIGGER_STATUS_PENDING":     1,
		"BUILD_TRIGGER_STATUS_ACCEPTED":    2,
		"BUILD_TRIGGER_STATUS_REJECTED":    3,
		"BUILD_TRIGGER_STATUS_CONSUMED":    4,
	}
)

func (x BuildTriggerStatus_BuildTriggerStatus) Enum() *BuildTriggerStatus_BuildTriggerStatus {
	p := new(BuildTriggerStatus_BuildTriggerStatus)
	*p = x
	return p
}

func (x BuildTriggerStatus_BuildTriggerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BuildTriggerStatus_BuildTriggerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_blanketops_common_v1_buildtrigger_proto_enumTypes[2].Descriptor()
}

func (BuildTriggerStatus_BuildTriggerStatus) Type() protoreflect.EnumType {
	return &file_blanketops_common_v1_buildtrigger_proto_enumTypes[2]
}

func (x BuildTriggerStatus_BuildTriggerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BuildTriggerStatus_BuildTriggerStatus.Descriptor instead.
func (BuildTriggerStatus_BuildTriggerStatus) EnumDescriptor() ([]byte, []int) {
	return file_blanketops_common_v1_buildtrigger_proto_rawDescGZIP(), []int{2, 0}
}

type BuildTriggerSource struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Source        BuildTriggerSource_BuildTriggerSource `protobuf:"varint,1,opt,name=source,proto3,enum=blanketops.common.v1.BuildTriggerSource_BuildTriggerSource" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildTriggerSource) Reset() {
	*x = BuildTriggerSource{}
	mi := &file_blanketops_common_v1_buildtrigger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildTriggerSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildTriggerSource) ProtoMessage() {}

func (x *BuildTriggerSource) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_common_v1_buildtrigger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildTriggerSource.ProtoReflect.Descriptor instead.
func (*BuildTriggerSource) Descriptor() ([]byte, []int) {
	return file_blanketops_common_v1_buildtrigger_proto_rawDescGZIP(), []int{0}
}

func (x *BuildTriggerSource) GetSource() BuildTriggerSource_BuildTriggerSource {
	if x != nil {
		return x.Source
	}
	return BuildTriggerSource_BUILD_TRIGGER_SOURCE_UNSPECIFIED
}

type BuildTriggerType struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Type          BuildTriggerType_BuildTriggerType `protobuf:"varint,1,opt,name=type,proto3,enum=blanketops.common.v1.BuildTriggerType_BuildTriggerType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildTriggerType) Reset() {
	*x = BuildTriggerType{}
	mi := &file_blanketops_common_v1_buildtrigger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildTriggerType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildTriggerType) ProtoMessage() {}

func (x *BuildTriggerType) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_common_v1_buildtrigger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildTriggerType.ProtoReflect.Descriptor instead.
func (*BuildTriggerType) Descriptor() ([]byte, []int) {
	return file_blanketops_common_v1_buildtrigger_proto_rawDescGZIP(), []int{1}
}

func (x *BuildTriggerType) GetType() BuildTriggerType_BuildTriggerType {
	if x != nil {
		return x.Type
	}
	return BuildTriggerType_BUILD_TRIGGER_TYPE_UNSPECIFIED
}

type BuildTriggerStatus struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Status        BuildTriggerStatus_BuildTriggerStatus `protobuf:"varint,1,opt,name=status,proto3,enum=blanketops.common.v1.BuildTriggerStatus_BuildTriggerStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildTriggerStatus) Reset() {
	*x = BuildTriggerStatus{}
	mi := &file_blanketops_common_v1_buildtrigger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildTriggerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildTriggerStatus) ProtoMessage() {}

func (x *BuildTriggerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_common_v1_buildtrigger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildTriggerStatus.ProtoReflect.Descriptor instead.
func (*BuildTriggerStatus) Descriptor() ([]byte, []int) {
	return file_blanketops_common_v1_buildtrigger_proto_rawDescGZIP(), []int{2}
}

func (x *BuildTriggerStatus) GetStatus() BuildTriggerStatus_BuildTriggerStatus {
	if x != nil {
		return x.Status
	}
	return BuildTriggerStatus_BUILD_TRIGGER_STATUS_UNSPECIFIED
}

var File_blanketops_common_v1_buildtrigger_proto protoreflect.FileDescriptor

const file_blanketops_common_v1_buildtrigger_proto_rawDesc = "" +
	"\n" +
	"'blanketops/common/v1/buildtrigger.proto\x12\x14blanketops.common.v1\"\x89\x02\n" +
	"\x12BuildTriggerSource\x12S\n" +
	"\x06source\x18\x01 \x01(\x0e2;.blanketops.common.v1.BuildTriggerSource.BuildTriggerSourceR\x06source\"\x9d\x01\n" +
	"\x12BuildTriggerSource\x12$\n" +
	" BUILD_TRIGGER_SOURCE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bBUILD_TRIGGER_SOURCE_GITHUB\x10\x01\x12\x1f\n" +
	"\x1bBUILD_TRIGGER_SOURCE_GITLAB\x10\x02\x12\x1f\n" +
	"\x1bBUILD_TRIGGER_SOURCE_MANUAL\x10\x03\"\xfb\x01\n" +
	"\x10BuildTriggerType\x12K\n" +
	"\x04type\x18\x01 \x01(\x0e27.blanketops.common.v1.BuildTriggerType.BuildTriggerTypeR\x04type\"\x99\x01\n" +
	"\x10BuildTriggerType\x12\"\n" +
	"\x1eBUILD_TRIGGER_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19BUILD_TRIGGER_TYPE_COMMIT\x10\x01\x12#\n" +
	"\x1fBUILD_TRIGGER_TYPE_PULL_REQUEST\x10\x02\x12\x1d\n" +
	"\x19BUILD_TRIGGER_TYPE_MANUAL\x10\x03\"\xb1\x02\n" +
	"\x12BuildTriggerStatus\x12S\n" +
	"\x06status\x18\x01 \x01(\x0e2;.blanketops.common.v1.BuildTriggerStatus.BuildTriggerStatusR\x06status\"\xc5\x01\n" +
	"\x12BuildTriggerStatus\x12$\n" +
	" BUILD_TRIGGER_STATUS_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cBUILD_TRIGGER_STATUS_PENDING\x10\x01\x12!\n" +
	"\x1dBUILD_TRIGGER_STATUS_ACCEPTED\x10\x02\x12!\n" +
	"\x1dBUILD_TRIGGER_STATUS_REJECTED\x10\x03\x12!\n" +
	"\x1dBUILD_TRIGGER_STATUS_CONSUMED\x10\x04BbZIgithub.com/blanketops/environments-contract/blanketops/common/v1;commonv1\xaa\x02\x14BlanketOps.Common.v1b\x06proto3"

var (
	file_blanketops_common_v1_buildtrigger_proto_rawDescOnce sync.Once
	file_blanketops_common_v1_buildtrigger_proto_rawDescData []byte
)

func file_blanketops_common_v1_buildtrigger_proto_rawDescGZIP() []byte {
	file_blanketops_common_v1_buildtrigger_proto_rawDescOnce.Do(func() {
		file_blanketops_common_v1_buildtrigger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blanketops_common_v1_buildtrigger_proto_rawDesc), len(file_blanketops_common_v1_buildtrigger_proto_rawDesc)))
	})
	return file_blanketops_common_v1_buildtrigger_proto_rawDescData
}

var file_blanketops_common_v1_buildtrigger_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_blanketops_common_v1_buildtrigger_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_blanketops_common_v1_buildtrigger_proto_goTypes = []any{
	(BuildTriggerSource_BuildTriggerSource)(0), // 0: blanketops.common.v1.BuildTriggerSource.BuildTriggerSource
	(BuildTriggerType_BuildTriggerType)(0),     // 1: blanketops.common.v1.BuildTriggerType.BuildTriggerType
	(BuildTriggerStatus_BuildTriggerStatus)(0), // 2: blanketops.common.v1.BuildTriggerStatus.BuildTriggerStatus
	(*BuildTriggerSource)(nil),                 // 3: blanketops.common.v1.BuildTriggerSource
	(*BuildTriggerType)(nil),                   // 4: blanketops.common.v1.BuildTriggerType
	(*BuildTriggerStatus)(nil),                 // 5: blanketops.common.v1.BuildTriggerStatus
}
var file_blanketops_common_v1_buildtrigger_proto_depIdxs = []int32{
	0, // 0: blanketops.common.v1.BuildTriggerSource.source:type_name -> blanketops.common.v1.BuildTriggerSource.BuildTriggerSource
	1, // 1: blanketops.common.v1.BuildTriggerType.type:type_name -> blanketops.common.v1.BuildTriggerType.BuildTriggerType
	2, // 2: blanketops.common.v1.BuildTriggerStatus.status:type_name -> blanketops.common.v1.BuildTriggerStatus.BuildTriggerStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_blanketops_common_v1_buildtrigger_proto_init() }
func file_blanketops_common_v1_buildtrigger_proto_init() {
	if File_blanketops_common_v1_buildtrigger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blanketops_common_v1_buildtrigger_proto_rawDesc), len(file_blanketops_common_v1_buildtrigger_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blanketops_common_v1_buildtrigger_proto_goTypes,
		DependencyIndexes: file_blanketops_common_v1_buildtrigger_proto_depIdxs,
		EnumInfos:         file_blanketops_common_v1_buildtrigger_proto_enumTypes,
		MessageInfos:      file_blanketops_common_v1_buildtrigger_proto_msgTypes,
	}.Build()
	File_blanketops_common_v1_buildtrigger_proto = out.File
	file_blanketops_common_v1_buildtrigger_proto_goTypes = nil
	file_blanketops_common_v1_buildtrigger_proto_depIdxs = nil
}
