//
//Copyright 2026 The BlanketOps Authors.
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//http://www.apache.org/licenses/LICENSE-2.0
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=none"
// @generated from file blanketops/common/v1/deployment.proto (package blanketops.common.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file blanketops/common/v1/deployment.proto.
 */
export const file_blanketops_common_v1_deployment: GenFile = /*@__PURE__*/
  fileDesc("CiVibGFua2V0b3BzL2NvbW1vbi92MS9kZXBsb3ltZW50LnByb3RvEhRibGFua2V0b3BzLmNvbW1vbi52MSLTAgoRRGVwbG95bWVudFJ1bnRpbWUSSgoHcnVudGltZRgBIAEoDjI5LmJsYW5rZXRvcHMuY29tbW9uLnYxLkRlcGxveW1lbnRSdW50aW1lLkRlcGxveW1lbnRSdW50aW1lIvEBChFEZXBsb3ltZW50UnVudGltZRIiCh5ERVBMT1lNRU5UX1JVTlRJTUVfVU5TUEVDSUZJRUQQABIrCidERVBMT1lNRU5UX1JVTlRJTUVfS1VCRVJORVRFU19DT05UQUlORVIQARImCiJERVBMT1lNRU5UX1JVTlRJTUVfS05BVElWRV9TRVJWSUNFEAISGwoXREVQTE9ZTUVOVF9SVU5USU1FX1dBU00QAxIeChpERVBMT1lNRU5UX1JVTlRJTUVfQVdTX0VDUxAEEiYKIkRFUExPWU1FTlRfUlVOVElNRV9BWlVSRV9DT05UQUlORVIQBSL8AQoWUmVjb25jaWxpYXRpb25TdHJhdGVneRJVCghzdHJhdGVneRgBIAEoDjJDLmJsYW5rZXRvcHMuY29tbW9uLnYxLlJlY29uY2lsaWF0aW9uU3RyYXRlZ3kuUmVjb25jaWxpYXRpb25TdHJhdGVneSKKAQoWUmVjb25jaWxpYXRpb25TdHJhdGVneRInCiNSRUNPTkNJTElBVElPTl9TVFJBVEVHWV9VTlNQRUNJRklFRBAAEiUKIVJFQ09OQ0lMSUFUSU9OX1NUUkFURUdZX0tVU1RPTUlaRRABEiAKHFJFQ09OQ0lMSUFUSU9OX1NUUkFURUdZX0hFTE0QAiKEAgoPRGVwbG95bWVudFBoYXNlEkQKBXBoYXNlGAEgASgOMjUuYmxhbmtldG9wcy5jb21tb24udjEuRGVwbG95bWVudFBoYXNlLkRlcGxveW1lbnRQaGFzZSKqAQoPRGVwbG95bWVudFBoYXNlEiAKHERFUExPWU1FTlRfUEhBU0VfVU5TUEVDSUZJRUQQABIcChhERVBMT1lNRU5UX1BIQVNFX1BFTkRJTkcQARIeChpERVBMT1lNRU5UX1BIQVNFX0RFUExPWUlORxACEhoKFkRFUExPWU1FTlRfUEhBU0VfUkVBRFkQAxIbChdERVBMT1lNRU5UX1BIQVNFX0ZBSUxFRBAEIoQCChJEZXBsb3ltZW50U3RyYXRlZ3kSTQoIc3RyYXRlZ3kYASABKA4yOy5ibGFua2V0b3BzLmNvbW1vbi52MS5EZXBsb3ltZW50U3RyYXRlZ3kuRGVwbG95bWVudFN0cmF0ZWd5Ip4BChJEZXBsb3ltZW50U3RyYXRlZ3kSIwofREVQTE9ZTUVOVF9TVFJBVEVHWV9VTlNQRUNJRklFRBAAEh8KG0RFUExPWU1FTlRfU1RSQVRFR1lfUk9MTElORxABEh4KGkRFUExPWU1FTlRfU1RSQVRFR1lfQ0FOQVJZEAISIgoeREVQTE9ZTUVOVF9TVFJBVEVHWV9CTFVFX0dSRUVOEANCYlpJZ2l0aHViLmNvbS9CbGFua2V0T3BzL2Vudmlyb25tZW50cy1jb250cmFjdC9ibGFua2V0b3BzL2NvbW1vbi92MTtjb21tb252MaoCFEJsYW5rZXRPcHMuQ29tbW9uLnYxYgZwcm90bzM");

/**
 * Target runtime backend. Top-level by design: referenced from
 * DeploymentSpec, DeploymentStatus, and ServiceUnitDeploymentStatus.
 *
 * @generated from message blanketops.common.v1.DeploymentRuntime
 */
export type DeploymentRuntime = Message<"blanketops.common.v1.DeploymentRuntime"> & {
  /**
   * @generated from field: blanketops.common.v1.DeploymentRuntime.DeploymentRuntime runtime = 1;
   */
  runtime: DeploymentRuntime_DeploymentRuntime;
};

/**
 * Describes the message blanketops.common.v1.DeploymentRuntime.
 * Use `create(DeploymentRuntimeSchema)` to create a new message.
 */
export const DeploymentRuntimeSchema: GenMessage<DeploymentRuntime> = /*@__PURE__*/
  messageDesc(file_blanketops_common_v1_deployment, 0);

/**
 * @generated from enum blanketops.common.v1.DeploymentRuntime.DeploymentRuntime
 */
export enum DeploymentRuntime_DeploymentRuntime {
  /**
   * @generated from enum value: DEPLOYMENT_RUNTIME_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Native Kubernetes Deployment + Service.
   *
   * @generated from enum value: DEPLOYMENT_RUNTIME_KUBERNETES_CONTAINER = 1;
   */
  KUBERNETES_CONTAINER = 1,

  /**
   * Knative Service, served via Kourier.
   *
   * @generated from enum value: DEPLOYMENT_RUNTIME_KNATIVE_SERVICE = 2;
   */
  KNATIVE_SERVICE = 2,

  /**
   * WebAssembly workload (future).
   *
   * @generated from enum value: DEPLOYMENT_RUNTIME_WASM = 3;
   */
  WASM = 3,

  /**
   * AWS ECS task (future).
   *
   * @generated from enum value: DEPLOYMENT_RUNTIME_AWS_ECS = 4;
   */
  AWS_ECS = 4,

  /**
   * Azure Container Instance (future).
   *
   * @generated from enum value: DEPLOYMENT_RUNTIME_AZURE_CONTAINER = 5;
   */
  AZURE_CONTAINER = 5,
}

/**
 * Describes the enum blanketops.common.v1.DeploymentRuntime.DeploymentRuntime.
 */
export const DeploymentRuntime_DeploymentRuntimeSchema: GenEnum<DeploymentRuntime_DeploymentRuntime> = /*@__PURE__*/
  enumDesc(file_blanketops_common_v1_deployment, 0, 0);

/**
 * @generated from message blanketops.common.v1.ReconciliationStrategy
 */
export type ReconciliationStrategy = Message<"blanketops.common.v1.ReconciliationStrategy"> & {
  /**
   * @generated from field: blanketops.common.v1.ReconciliationStrategy.ReconciliationStrategy strategy = 1;
   */
  strategy: ReconciliationStrategy_ReconciliationStrategy;
};

/**
 * Describes the message blanketops.common.v1.ReconciliationStrategy.
 * Use `create(ReconciliationStrategySchema)` to create a new message.
 */
export const ReconciliationStrategySchema: GenMessage<ReconciliationStrategy> = /*@__PURE__*/
  messageDesc(file_blanketops_common_v1_deployment, 1);

/**
 * Manifest application strategy when GitOps delivery is used.
 *
 * @generated from enum blanketops.common.v1.ReconciliationStrategy.ReconciliationStrategy
 */
export enum ReconciliationStrategy_ReconciliationStrategy {
  /**
   * @generated from enum value: RECONCILIATION_STRATEGY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Kustomize overlays — standard for BlanketOps-owned manifests.
   *
   * @generated from enum value: RECONCILIATION_STRATEGY_KUSTOMIZE = 1;
   */
  KUSTOMIZE = 1,

  /**
   * Helm — reserved for upstream third-party charts.
   *
   * @generated from enum value: RECONCILIATION_STRATEGY_HELM = 2;
   */
  HELM = 2,
}

/**
 * Describes the enum blanketops.common.v1.ReconciliationStrategy.ReconciliationStrategy.
 */
export const ReconciliationStrategy_ReconciliationStrategySchema: GenEnum<ReconciliationStrategy_ReconciliationStrategy> = /*@__PURE__*/
  enumDesc(file_blanketops_common_v1_deployment, 1, 0);

/**
 * @generated from message blanketops.common.v1.DeploymentPhase
 */
export type DeploymentPhase = Message<"blanketops.common.v1.DeploymentPhase"> & {
  /**
   * @generated from field: blanketops.common.v1.DeploymentPhase.DeploymentPhase phase = 1;
   */
  phase: DeploymentPhase_DeploymentPhase;
};

/**
 * Describes the message blanketops.common.v1.DeploymentPhase.
 * Use `create(DeploymentPhaseSchema)` to create a new message.
 */
export const DeploymentPhaseSchema: GenMessage<DeploymentPhase> = /*@__PURE__*/
  messageDesc(file_blanketops_common_v1_deployment, 2);

/**
 * Lifecycle phase of this Deployment.
 *
 * @generated from enum blanketops.common.v1.DeploymentPhase.DeploymentPhase
 */
export enum DeploymentPhase_DeploymentPhase {
  /**
   * @generated from enum value: DEPLOYMENT_PHASE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Waiting for service units or GitOps sources to be ready.
   *
   * @generated from enum value: DEPLOYMENT_PHASE_PENDING = 1;
   */
  PENDING = 1,

  /**
   * Workloads are being rolled out.
   *
   * @generated from enum value: DEPLOYMENT_PHASE_DEPLOYING = 2;
   */
  DEPLOYING = 2,

  /**
   * All service units are deployed and healthy.
   *
   * @generated from enum value: DEPLOYMENT_PHASE_READY = 3;
   */
  READY = 3,

  /**
   * One or more service units failed to deploy.
   *
   * @generated from enum value: DEPLOYMENT_PHASE_FAILED = 4;
   */
  FAILED = 4,
}

/**
 * Describes the enum blanketops.common.v1.DeploymentPhase.DeploymentPhase.
 */
export const DeploymentPhase_DeploymentPhaseSchema: GenEnum<DeploymentPhase_DeploymentPhase> = /*@__PURE__*/
  enumDesc(file_blanketops_common_v1_deployment, 2, 0);

/**
 * @generated from message blanketops.common.v1.DeploymentStrategy
 */
export type DeploymentStrategy = Message<"blanketops.common.v1.DeploymentStrategy"> & {
  /**
   * @generated from field: blanketops.common.v1.DeploymentStrategy.DeploymentStrategy strategy = 1;
   */
  strategy: DeploymentStrategy_DeploymentStrategy;
};

/**
 * Describes the message blanketops.common.v1.DeploymentStrategy.
 * Use `create(DeploymentStrategySchema)` to create a new message.
 */
export const DeploymentStrategySchema: GenMessage<DeploymentStrategy> = /*@__PURE__*/
  messageDesc(file_blanketops_common_v1_deployment, 3);

/**
 * Rollout strategy applied by the runtime.
 *
 * @generated from enum blanketops.common.v1.DeploymentStrategy.DeploymentStrategy
 */
export enum DeploymentStrategy_DeploymentStrategy {
  /**
   * @generated from enum value: DEPLOYMENT_STRATEGY_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Rolling update — default.
   *
   * @generated from enum value: DEPLOYMENT_STRATEGY_ROLLING = 1;
   */
  ROLLING = 1,

  /**
   * Canary rollout (future).
   *
   * @generated from enum value: DEPLOYMENT_STRATEGY_CANARY = 2;
   */
  CANARY = 2,

  /**
   * Blue/green rollout (future).
   *
   * @generated from enum value: DEPLOYMENT_STRATEGY_BLUE_GREEN = 3;
   */
  BLUE_GREEN = 3,
}

/**
 * Describes the enum blanketops.common.v1.DeploymentStrategy.DeploymentStrategy.
 */
export const DeploymentStrategy_DeploymentStrategySchema: GenEnum<DeploymentStrategy_DeploymentStrategy> = /*@__PURE__*/
  enumDesc(file_blanketops_common_v1_deployment, 3, 0);

