//
// Copyright 2026 The BlanketOps Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// =============================================================================
// blanketops/common/v1/domain.proto
//
// Domain-specific shared types used by networks.blanketops.dev resources.
//
// All enum values are wrapped in a message (DomainPhase, DomainTLSStrategy,
// DomainTLSStatus) — consistent with the RoutePhase / RouteRuntime /
// RouteTLSStatus wrapper pattern in common/v1/route.proto.
//
// Consumers:
//   blanketops/networks/v1alpha1/domain.proto
//   resolution/domain/contract_adapter.go
// =============================================================================

// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=none"
// @generated from file blanketops/common/v1/domain.proto (package blanketops.common.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file blanketops/common/v1/domain.proto.
 */
export const file_blanketops_common_v1_domain: GenFile = /*@__PURE__*/
  fileDesc("CiFibGFua2V0b3BzL2NvbW1vbi92MS9kb21haW4ucHJvdG8SFGJsYW5rZXRvcHMuY29tbW9uLnYxIuMBCgtEb21haW5QaGFzZRI8CgVwaGFzZRgBIAEoDjItLmJsYW5rZXRvcHMuY29tbW9uLnYxLkRvbWFpblBoYXNlLkRvbWFpblBoYXNlIpUBCgtEb21haW5QaGFzZRIcChhET01BSU5fUEhBU0VfVU5TUEVDSUZJRUQQABIYChRET01BSU5fUEhBU0VfUEVORElORxABEh0KGURPTUFJTl9QSEFTRV9QUk9WSVNJT05JTkcQAhIWChJET01BSU5fUEhBU0VfUkVBRFkQAxIXChNET01BSU5fUEhBU0VfRkFJTEVEEAQi3AEKEURvbWFpblRMU1N0cmF0ZWd5EksKCHN0cmF0ZWd5GAEgASgOMjkuYmxhbmtldG9wcy5jb21tb24udjEuRG9tYWluVExTU3RyYXRlZ3kuRG9tYWluVExTU3RyYXRlZ3kiegoRRG9tYWluVExTU3RyYXRlZ3kSIwofRE9NQUlOX1RMU19TVFJBVEVHWV9VTlNQRUNJRklFRBAAEiAKHERPTUFJTl9UTFNfU1RSQVRFR1lfUExBVEZPUk0QARIeChpET01BSU5fVExTX1NUUkFURUdZX0NVU1RPTRACIo8CCg9Eb21haW5UTFNTdGF0dXMSRQoGc3RhdHVzGAEgASgOMjUuYmxhbmtldG9wcy5jb21tb24udjEuRG9tYWluVExTU3RhdHVzLkRvbWFpblRMU1N0YXR1cyK0AQoPRG9tYWluVExTU3RhdHVzEiEKHURPTUFJTl9UTFNfU1RBVFVTX1VOU1BFQ0lGSUVEEAASHgoaRE9NQUlOX1RMU19TVEFUVVNfRElTQUJMRUQQARIiCh5ET01BSU5fVExTX1NUQVRVU19QUk9WSVNJT05JTkcQAhIcChhET01BSU5fVExTX1NUQVRVU19BQ1RJVkUQAxIcChhET01BSU5fVExTX1NUQVRVU19GQUlMRUQQBEJvQgtEb21haW5Qcm90b1pJZ2l0aHViLmNvbS9CbGFua2V0T3BzL2Vudmlyb25tZW50cy1jb250cmFjdC9ibGFua2V0b3BzL2NvbW1vbi92MTtjb21tb252MaoCFEJsYW5rZXRPcHMuQ29tbW9uLnYxYgZwcm90bzM");

/**
 * =============================================================================
 * DomainPhase
 *
 * Lifecycle phase of a Domain CR. Set exclusively by the controller.
 * =============================================================================
 *
 * @generated from message blanketops.common.v1.DomainPhase
 */
export type DomainPhase = Message<"blanketops.common.v1.DomainPhase"> & {
  /**
   * phase is the current lifecycle value.
   *
   * @generated from field: blanketops.common.v1.DomainPhase.DomainPhase phase = 1;
   */
  phase: DomainPhase_DomainPhase;
};

/**
 * Describes the message blanketops.common.v1.DomainPhase.
 * Use `create(DomainPhaseSchema)` to create a new message.
 */
export const DomainPhaseSchema: GenMessage<DomainPhase> = /*@__PURE__*/
  messageDesc(file_blanketops_common_v1_domain, 0);

/**
 * @generated from enum blanketops.common.v1.DomainPhase.DomainPhase
 */
export enum DomainPhase_DomainPhase {
  /**
   * Unset — should never appear in a reconciled CR.
   *
   * @generated from enum value: DOMAIN_PHASE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Controller has accepted the CR but cert/mapping work has not started.
   *
   * @generated from enum value: DOMAIN_PHASE_PENDING = 1;
   */
  PENDING = 1,

  /**
   * Cert or DomainMapping is being provisioned (Issuer, Certificate, or
   * DomainClaim are in-progress).
   *
   * @generated from enum value: DOMAIN_PHASE_PROVISIONING = 2;
   */
  PROVISIONING = 2,

  /**
   * Cert is issued, DomainMapping is active, and mTLS (when enforced) is
   * wired. The host is reachable.
   *
   * @generated from enum value: DOMAIN_PHASE_READY = 3;
   */
  READY = 3,

  /**
   * Terminal failure — cert issuance failed, DomainMapping rejected, or
   * an ACME HTTP01 challenge could not be satisfied.
   *
   * @generated from enum value: DOMAIN_PHASE_FAILED = 4;
   */
  FAILED = 4,
}

/**
 * Describes the enum blanketops.common.v1.DomainPhase.DomainPhase.
 */
export const DomainPhase_DomainPhaseSchema: GenEnum<DomainPhase_DomainPhase> = /*@__PURE__*/
  enumDesc(file_blanketops_common_v1_domain, 0, 0);

/**
 * =============================================================================
 * DomainTLSStrategy
 *
 * Controls which cert provisioning path the Domain controller takes.
 *
 *   platform — The platform wildcard cert (*.dev.host) already covers this
 *              host via a DNS01 ClusterIssuer. Controller emits DomainClaim +
 *              DomainMapping only — no Certificate work is needed.
 *
 *   custom   — Client-owned zone (e.g. client-a.co.za). Controller emits
 *              Issuer + DomainClaim + DomainMapping + Certificate. HTTP01
 *              ACME challenge via the nginx solver in the tenant namespace.
 * =============================================================================
 *
 * @generated from message blanketops.common.v1.DomainTLSStrategy
 */
export type DomainTLSStrategy = Message<"blanketops.common.v1.DomainTLSStrategy"> & {
  /**
   * strategy is the selected TLS provisioning path.
   *
   * @generated from field: blanketops.common.v1.DomainTLSStrategy.DomainTLSStrategy strategy = 1;
   */
  strategy: DomainTLSStrategy_DomainTLSStrategy;
};

/**
 * Describes the message blanketops.common.v1.DomainTLSStrategy.
 * Use `create(DomainTLSStrategySchema)` to create a new message.
 */
export const DomainTLSStrategySchema: GenMessage<DomainTLSStrategy> = /*@__PURE__*/
  messageDesc(file_blanketops_common_v1_domain, 1);

/**
 * @generated from enum blanketops.common.v1.DomainTLSStrategy.DomainTLSStrategy
 */
export enum DomainTLSStrategy_DomainTLSStrategy {
  /**
   * @generated from enum value: DOMAIN_TLS_STRATEGY_UNSPECIFIED = 0;
   */
  DOMAIN_TLS_STRATEGY_UNSPECIFIED = 0,

  /**
   * Platform wildcard cert path — DNS01 ClusterIssuer, already issued.
   * Controller emits DomainClaim + DomainMapping only.
   *
   * @generated from enum value: DOMAIN_TLS_STRATEGY_PLATFORM = 1;
   */
  DOMAIN_TLS_STRATEGY_PLATFORM = 1,

  /**
   * Client-owned zone — HTTP01 cert path.
   * Controller emits Issuer + DomainClaim + DomainMapping + Certificate.
   *
   * @generated from enum value: DOMAIN_TLS_STRATEGY_CUSTOM = 2;
   */
  DOMAIN_TLS_STRATEGY_CUSTOM = 2,
}

/**
 * Describes the enum blanketops.common.v1.DomainTLSStrategy.DomainTLSStrategy.
 */
export const DomainTLSStrategy_DomainTLSStrategySchema: GenEnum<DomainTLSStrategy_DomainTLSStrategy> = /*@__PURE__*/
  enumDesc(file_blanketops_common_v1_domain, 1, 0);

/**
 * =============================================================================
 * DomainTLSStatus
 *
 * Observed TLS provisioning state for a Domain. Set by the controller.
 * =============================================================================
 *
 * @generated from message blanketops.common.v1.DomainTLSStatus
 */
export type DomainTLSStatus = Message<"blanketops.common.v1.DomainTLSStatus"> & {
  /**
   * status is the current TLS provisioning state.
   *
   * @generated from field: blanketops.common.v1.DomainTLSStatus.DomainTLSStatus status = 1;
   */
  status: DomainTLSStatus_DomainTLSStatus;
};

/**
 * Describes the message blanketops.common.v1.DomainTLSStatus.
 * Use `create(DomainTLSStatusSchema)` to create a new message.
 */
export const DomainTLSStatusSchema: GenMessage<DomainTLSStatus> = /*@__PURE__*/
  messageDesc(file_blanketops_common_v1_domain, 2);

/**
 * @generated from enum blanketops.common.v1.DomainTLSStatus.DomainTLSStatus
 */
export enum DomainTLSStatus_DomainTLSStatus {
  /**
   * @generated from enum value: DOMAIN_TLS_STATUS_UNSPECIFIED = 0;
   */
  DOMAIN_TLS_STATUS_UNSPECIFIED = 0,

  /**
   * TLS is not configured for this domain.
   *
   * @generated from enum value: DOMAIN_TLS_STATUS_DISABLED = 1;
   */
  DOMAIN_TLS_STATUS_DISABLED = 1,

  /**
   * Cert issuance or DomainMapping creation is in progress.
   *
   * @generated from enum value: DOMAIN_TLS_STATUS_PROVISIONING = 2;
   */
  DOMAIN_TLS_STATUS_PROVISIONING = 2,

  /**
   * Cert is valid and DomainMapping is serving TLS traffic.
   *
   * @generated from enum value: DOMAIN_TLS_STATUS_ACTIVE = 3;
   */
  DOMAIN_TLS_STATUS_ACTIVE = 3,

  /**
   * Cert issuance failed or the cert has expired.
   *
   * @generated from enum value: DOMAIN_TLS_STATUS_FAILED = 4;
   */
  DOMAIN_TLS_STATUS_FAILED = 4,
}

/**
 * Describes the enum blanketops.common.v1.DomainTLSStatus.DomainTLSStatus.
 */
export const DomainTLSStatus_DomainTLSStatusSchema: GenEnum<DomainTLSStatus_DomainTLSStatus> = /*@__PURE__*/
  enumDesc(file_blanketops_common_v1_domain, 2, 0);

