//
//Copyright 2026 The BlanketOps Authors.
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//http://www.apache.org/licenses/LICENSE-2.0
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=none"
// @generated from file blanketops/common/v1/metadata.proto (package blanketops.common.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file blanketops/common/v1/metadata.proto.
 */
export const file_blanketops_common_v1_metadata: GenFile = /*@__PURE__*/
  fileDesc("CiNibGFua2V0b3BzL2NvbW1vbi92MS9tZXRhZGF0YS5wcm90bxIUYmxhbmtldG9wcy5jb21tb24udjEiowEKCE1ldGFkYXRhEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSOgoGbGFiZWxzGAMgAygLMiouYmxhbmtldG9wcy5jb21tb24udjEuTWV0YWRhdGEuTGFiZWxzRW50cnkSEgoKZ2VuZXJhdGlvbhgEIAEoAxotCgtMYWJlbHNFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAk6AjgBQm5aVWdpdGh1Yi5jb20vbnRsYWxldHNpNzAvYmxhbmtldG9wcy1lbnZpcm9ubWVudHMtY29udHJhY3QvYmxhbmtldG9wcy9jb21tb24vdjE7Y29tbW9udjGqAhRCbGFua2V0T3BzLkNvbW1vbi52MWIGcHJvdG8z");

/**
 * @generated from message blanketops.common.v1.Metadata
 */
export type Metadata = Message<"blanketops.common.v1.Metadata"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: map<string, string> labels = 3;
   */
  labels: { [key: string]: string };

  /**
   * @generated from field: int64 generation = 4;
   */
  generation: bigint;
};

/**
 * Describes the message blanketops.common.v1.Metadata.
 * Use `create(MetadataSchema)` to create a new message.
 */
export const MetadataSchema: GenMessage<Metadata> = /*@__PURE__*/
  messageDesc(file_blanketops_common_v1_metadata, 0);

