//
//Copyright 2026 The BlanketOps Authors.
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//http://www.apache.org/licenses/LICENSE-2.0
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// @generated by protoc-gen-es v2.2.5 with parameter "target=ts,import_extension=none"
// @generated from file blanketops/common/v1/package.proto (package blanketops.common.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file blanketops/common/v1/package.proto.
 */
export const file_blanketops_common_v1_package: GenFile = /*@__PURE__*/
  fileDesc("CiJibGFua2V0b3BzL2NvbW1vbi92MS9wYWNrYWdlLnByb3RvEhRibGFua2V0b3BzLmNvbW1vbi52MSKLAQoMUGFja2FnZVBoYXNlInsKDFBhY2thZ2VQaGFzZRIdChlQQUNLQUdFX1BIQVNFX1VOU1BFQ0lGSUVEEAASGQoVUEFDS0FHRV9QSEFTRV9QRU5ESU5HEAESFwoTUEFDS0FHRV9QSEFTRV9SRUFEWRACEhgKFFBBQ0tBR0VfUEhBU0VfRkFJTEVEEANCblpVZ2l0aHViLmNvbS9udGxhbGV0c2k3MC9ibGFua2V0b3BzLWVudmlyb25tZW50cy1jb250cmFjdC9ibGFua2V0b3BzL2NvbW1vbi92MTtjb21tb252MaoCFEJsYW5rZXRPcHMuQ29tbW9uLnYxYgZwcm90bzM");

/**
 * @generated from message blanketops.common.v1.PackagePhase
 */
export type PackagePhase = Message<"blanketops.common.v1.PackagePhase"> & {
};

/**
 * Describes the message blanketops.common.v1.PackagePhase.
 * Use `create(PackagePhaseSchema)` to create a new message.
 */
export const PackagePhaseSchema: GenMessage<PackagePhase> = /*@__PURE__*/
  messageDesc(file_blanketops_common_v1_package, 0);

/**
 * @generated from enum blanketops.common.v1.PackagePhase.PackagePhase
 */
export enum PackagePhase_PackagePhase {
  /**
   * @generated from enum value: PACKAGE_PHASE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Waiting for sources to be ready or reconciliation to complete.
   *
   * @generated from enum value: PACKAGE_PHASE_PENDING = 1;
   */
  PENDING = 1,

  /**
   * The package is reconciled against the state repository.
   *
   * @generated from enum value: PACKAGE_PHASE_READY = 2;
   */
  READY = 2,

  /**
   * Reconciliation failed. Check message and diff_output.
   *
   * @generated from enum value: PACKAGE_PHASE_FAILED = 3;
   */
  FAILED = 3,
}

/**
 * Describes the enum blanketops.common.v1.PackagePhase.PackagePhase.
 */
export const PackagePhase_PackagePhaseSchema: GenEnum<PackagePhase_PackagePhase> = /*@__PURE__*/
  enumDesc(file_blanketops_common_v1_package, 0, 0);

