//
//Copyright 2026 The BlanketOps Authors.
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//http://www.apache.org/licenses/LICENSE-2.0
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: blanketops/common/v1/package.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PackagePhase_PackagePhase int32

const (
	PackagePhase_PACKAGE_PHASE_UNSPECIFIED PackagePhase_PackagePhase = 0
	PackagePhase_PACKAGE_PHASE_PENDING     PackagePhase_PackagePhase = 1
	PackagePhase_PACKAGE_PHASE_READY       PackagePhase_PackagePhase = 2
	PackagePhase_PACKAGE_PHASE_FAILED      PackagePhase_PackagePhase = 3
)

// Enum value maps for PackagePhase_PackagePhase.
var (
	PackagePhase_PackagePhase_name = map[int32]string{
		0: "PACKAGE_PHASE_UNSPECIFIED",
		1: "PACKAGE_PHASE_PENDING",
		2: "PACKAGE_PHASE_READY",
		3: "PACKAGE_PHASE_FAILED",
	}
	PackagePhase_PackagePhase_value = map[string]int32{
		"PACKAGE_PHASE_UNSPECIFIED": 0,
		"PACKAGE_PHASE_PENDING":     1,
		"PACKAGE_PHASE_READY":       2,
		"PACKAGE_PHASE_FAILED":      3,
	}
)

func (x PackagePhase_PackagePhase) Enum() *PackagePhase_PackagePhase {
	p := new(PackagePhase_PackagePhase)
	*p = x
	return p
}

func (x PackagePhase_PackagePhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PackagePhase_PackagePhase) Descriptor() protoreflect.EnumDescriptor {
	return file_blanketops_common_v1_package_proto_enumTypes[0].Descriptor()
}

func (PackagePhase_PackagePhase) Type() protoreflect.EnumType {
	return &file_blanketops_common_v1_package_proto_enumTypes[0]
}

func (x PackagePhase_PackagePhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PackagePhase_PackagePhase.Descriptor instead.
func (PackagePhase_PackagePhase) EnumDescriptor() ([]byte, []int) {
	return file_blanketops_common_v1_package_proto_rawDescGZIP(), []int{0, 0}
}

type PackagePhase struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Phase         PackagePhase_PackagePhase `protobuf:"varint,1,opt,name=phase,proto3,enum=blanketops.common.v1.PackagePhase_PackagePhase" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackagePhase) Reset() {
	*x = PackagePhase{}
	mi := &file_blanketops_common_v1_package_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackagePhase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackagePhase) ProtoMessage() {}

func (x *PackagePhase) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_common_v1_package_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackagePhase.ProtoReflect.Descriptor instead.
func (*PackagePhase) Descriptor() ([]byte, []int) {
	return file_blanketops_common_v1_package_proto_rawDescGZIP(), []int{0}
}

func (x *PackagePhase) GetPhase() PackagePhase_PackagePhase {
	if x != nil {
		return x.Phase
	}
	return PackagePhase_PACKAGE_PHASE_UNSPECIFIED
}

var File_blanketops_common_v1_package_proto protoreflect.FileDescriptor

const file_blanketops_common_v1_package_proto_rawDesc = "" +
	"\n" +
	"\"blanketops/common/v1/package.proto\x12\x14blanketops.common.v1\"\xd2\x01\n" +
	"\fPackagePhase\x12E\n" +
	"\x05phase\x18\x01 \x01(\x0e2/.blanketops.common.v1.PackagePhase.PackagePhaseR\x05phase\"{\n" +
	"\fPackagePhase\x12\x1d\n" +
	"\x19PACKAGE_PHASE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PACKAGE_PHASE_PENDING\x10\x01\x12\x17\n" +
	"\x13PACKAGE_PHASE_READY\x10\x02\x12\x18\n" +
	"\x14PACKAGE_PHASE_FAILED\x10\x03BbZIgithub.com/BlanketOps/environments-contract/blanketops/common/v1;commonv1\xaa\x02\x14BlanketOps.Common.v1b\x06proto3"

var (
	file_blanketops_common_v1_package_proto_rawDescOnce sync.Once
	file_blanketops_common_v1_package_proto_rawDescData []byte
)

func file_blanketops_common_v1_package_proto_rawDescGZIP() []byte {
	file_blanketops_common_v1_package_proto_rawDescOnce.Do(func() {
		file_blanketops_common_v1_package_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blanketops_common_v1_package_proto_rawDesc), len(file_blanketops_common_v1_package_proto_rawDesc)))
	})
	return file_blanketops_common_v1_package_proto_rawDescData
}

var file_blanketops_common_v1_package_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blanketops_common_v1_package_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_blanketops_common_v1_package_proto_goTypes = []any{
	(PackagePhase_PackagePhase)(0), // 0: blanketops.common.v1.PackagePhase.PackagePhase
	(*PackagePhase)(nil),           // 1: blanketops.common.v1.PackagePhase
}
var file_blanketops_common_v1_package_proto_depIdxs = []int32{
	0, // 0: blanketops.common.v1.PackagePhase.phase:type_name -> blanketops.common.v1.PackagePhase.PackagePhase
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_blanketops_common_v1_package_proto_init() }
func file_blanketops_common_v1_package_proto_init() {
	if File_blanketops_common_v1_package_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blanketops_common_v1_package_proto_rawDesc), len(file_blanketops_common_v1_package_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blanketops_common_v1_package_proto_goTypes,
		DependencyIndexes: file_blanketops_common_v1_package_proto_depIdxs,
		EnumInfos:         file_blanketops_common_v1_package_proto_enumTypes,
		MessageInfos:      file_blanketops_common_v1_package_proto_msgTypes,
	}.Build()
	File_blanketops_common_v1_package_proto = out.File
	file_blanketops_common_v1_package_proto_goTypes = nil
	file_blanketops_common_v1_package_proto_depIdxs = nil
}
