//
//Copyright 2026 The BlanketOps Authors.
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//http://www.apache.org/licenses/LICENSE-2.0
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: blanketops/common/v1/serviceunit.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceUnitDeploymentPhase_ServiceUnitDeploymentPhase int32

const (
	ServiceUnitDeploymentPhase_SERVICE_UNIT_DEPLOYMENT_PHASE_UNSPECIFIED ServiceUnitDeploymentPhase_ServiceUnitDeploymentPhase = 0
	ServiceUnitDeploymentPhase_SERVICE_UNIT_DEPLOYMENT_PHASE_PENDING     ServiceUnitDeploymentPhase_ServiceUnitDeploymentPhase = 1
	ServiceUnitDeploymentPhase_SERVICE_UNIT_DEPLOYMENT_PHASE_DEPLOYING   ServiceUnitDeploymentPhase_ServiceUnitDeploymentPhase = 2
	ServiceUnitDeploymentPhase_SERVICE_UNIT_DEPLOYMENT_PHASE_READY       ServiceUnitDeploymentPhase_ServiceUnitDeploymentPhase = 3
	ServiceUnitDeploymentPhase_SERVICE_UNIT_DEPLOYMENT_PHASE_FAILED      ServiceUnitDeploymentPhase_ServiceUnitDeploymentPhase = 4
)

// Enum value maps for ServiceUnitDeploymentPhase_ServiceUnitDeploymentPhase.
var (
	ServiceUnitDeploymentPhase_ServiceUnitDeploymentPhase_name = map[int32]string{
		0: "SERVICE_UNIT_DEPLOYMENT_PHASE_UNSPECIFIED",
		1: "SERVICE_UNIT_DEPLOYMENT_PHASE_PENDING",
		2: "SERVICE_UNIT_DEPLOYMENT_PHASE_DEPLOYING",
		3: "SERVICE_UNIT_DEPLOYMENT_PHASE_READY",
		4: "SERVICE_UNIT_DEPLOYMENT_PHASE_FAILED",
	}
	ServiceUnitDeploymentPhase_ServiceUnitDeploymentPhase_value = map[string]int32{
		"SERVICE_UNIT_DEPLOYMENT_PHASE_UNSPECIFIED": 0,
		"SERVICE_UNIT_DEPLOYMENT_PHASE_PENDING":     1,
		"SERVICE_UNIT_DEPLOYMENT_PHASE_DEPLOYING":   2,
		"SERVICE_UNIT_DEPLOYMENT_PHASE_READY":       3,
		"SERVICE_UNIT_DEPLOYMENT_PHASE_FAILED":      4,
	}
)

func (x ServiceUnitDeploymentPhase_ServiceUnitDeploymentPhase) Enum() *ServiceUnitDeploymentPhase_ServiceUnitDeploymentPhase {
	p := new(ServiceUnitDeploymentPhase_ServiceUnitDeploymentPhase)
	*p = x
	return p
}

func (x ServiceUnitDeploymentPhase_ServiceUnitDeploymentPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceUnitDeploymentPhase_ServiceUnitDeploymentPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_blanketops_common_v1_serviceunit_proto_enumTypes[0].Descriptor()
}

func (ServiceUnitDeploymentPhase_ServiceUnitDeploymentPhase) Type() protoreflect.EnumType {
	return &file_blanketops_common_v1_serviceunit_proto_enumTypes[0]
}

func (x ServiceUnitDeploymentPhase_ServiceUnitDeploymentPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceUnitDeploymentPhase_ServiceUnitDeploymentPhase.Descriptor instead.
func (ServiceUnitDeploymentPhase_ServiceUnitDeploymentPhase) EnumDescriptor() ([]byte, []int) {
	return file_blanketops_common_v1_serviceunit_proto_rawDescGZIP(), []int{0, 0}
}

type ServiceUnitType_ServiceUnitType int32

const (
	ServiceUnitType_SERVICE_UNIT_TYPE_UNSPECIFIED ServiceUnitType_ServiceUnitType = 0
	ServiceUnitType_SERVICE_UNIT_TYPE_STATIC      ServiceUnitType_ServiceUnitType = 1
	ServiceUnitType_SERVICE_UNIT_TYPE_BUILD       ServiceUnitType_ServiceUnitType = 2
	ServiceUnitType_SERVICE_UNIT_TYPE_SUPPLYCHAIN ServiceUnitType_ServiceUnitType = 3
)

// Enum value maps for ServiceUnitType_ServiceUnitType.
var (
	ServiceUnitType_ServiceUnitType_name = map[int32]string{
		0: "SERVICE_UNIT_TYPE_UNSPECIFIED",
		1: "SERVICE_UNIT_TYPE_STATIC",
		2: "SERVICE_UNIT_TYPE_BUILD",
		3: "SERVICE_UNIT_TYPE_SUPPLYCHAIN",
	}
	ServiceUnitType_ServiceUnitType_value = map[string]int32{
		"SERVICE_UNIT_TYPE_UNSPECIFIED": 0,
		"SERVICE_UNIT_TYPE_STATIC":      1,
		"SERVICE_UNIT_TYPE_BUILD":       2,
		"SERVICE_UNIT_TYPE_SUPPLYCHAIN": 3,
	}
)

func (x ServiceUnitType_ServiceUnitType) Enum() *ServiceUnitType_ServiceUnitType {
	p := new(ServiceUnitType_ServiceUnitType)
	*p = x
	return p
}

func (x ServiceUnitType_ServiceUnitType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceUnitType_ServiceUnitType) Descriptor() protoreflect.EnumDescriptor {
	return file_blanketops_common_v1_serviceunit_proto_enumTypes[1].Descriptor()
}

func (ServiceUnitType_ServiceUnitType) Type() protoreflect.EnumType {
	return &file_blanketops_common_v1_serviceunit_proto_enumTypes[1]
}

func (x ServiceUnitType_ServiceUnitType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceUnitType_ServiceUnitType.Descriptor instead.
func (ServiceUnitType_ServiceUnitType) EnumDescriptor() ([]byte, []int) {
	return file_blanketops_common_v1_serviceunit_proto_rawDescGZIP(), []int{1, 0}
}

type ServiceUnitRuntime_ServiceUnitRuntime int32

const (
	ServiceUnitRuntime_SERVICE_UNIT_RUNTIME_UNSPECIFIED ServiceUnitRuntime_ServiceUnitRuntime = 0
	ServiceUnitRuntime_SERVICE_UNIT_RUNTIME_KUBERNETES  ServiceUnitRuntime_ServiceUnitRuntime = 1
	ServiceUnitRuntime_SERVICE_UNIT_RUNTIME_KNATIVE     ServiceUnitRuntime_ServiceUnitRuntime = 2
	ServiceUnitRuntime_SERVICE_UNIT_RUNTIME_ECS         ServiceUnitRuntime_ServiceUnitRuntime = 3
	ServiceUnitRuntime_SERVICE_UNIT_RUNTIME_WASM        ServiceUnitRuntime_ServiceUnitRuntime = 4
)

// Enum value maps for ServiceUnitRuntime_ServiceUnitRuntime.
var (
	ServiceUnitRuntime_ServiceUnitRuntime_name = map[int32]string{
		0: "SERVICE_UNIT_RUNTIME_UNSPECIFIED",
		1: "SERVICE_UNIT_RUNTIME_KUBERNETES",
		2: "SERVICE_UNIT_RUNTIME_KNATIVE",
		3: "SERVICE_UNIT_RUNTIME_ECS",
		4: "SERVICE_UNIT_RUNTIME_WASM",
	}
	ServiceUnitRuntime_ServiceUnitRuntime_value = map[string]int32{
		"SERVICE_UNIT_RUNTIME_UNSPECIFIED": 0,
		"SERVICE_UNIT_RUNTIME_KUBERNETES":  1,
		"SERVICE_UNIT_RUNTIME_KNATIVE":     2,
		"SERVICE_UNIT_RUNTIME_ECS":         3,
		"SERVICE_UNIT_RUNTIME_WASM":        4,
	}
)

func (x ServiceUnitRuntime_ServiceUnitRuntime) Enum() *ServiceUnitRuntime_ServiceUnitRuntime {
	p := new(ServiceUnitRuntime_ServiceUnitRuntime)
	*p = x
	return p
}

func (x ServiceUnitRuntime_ServiceUnitRuntime) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceUnitRuntime_ServiceUnitRuntime) Descriptor() protoreflect.EnumDescriptor {
	return file_blanketops_common_v1_serviceunit_proto_enumTypes[2].Descriptor()
}

func (ServiceUnitRuntime_ServiceUnitRuntime) Type() protoreflect.EnumType {
	return &file_blanketops_common_v1_serviceunit_proto_enumTypes[2]
}

func (x ServiceUnitRuntime_ServiceUnitRuntime) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceUnitRuntime_ServiceUnitRuntime.Descriptor instead.
func (ServiceUnitRuntime_ServiceUnitRuntime) EnumDescriptor() ([]byte, []int) {
	return file_blanketops_common_v1_serviceunit_proto_rawDescGZIP(), []int{2, 0}
}

type ServiceUnitDeploymentPhase struct {
	state         protoimpl.MessageState                                `protogen:"open.v1"`
	Phase         ServiceUnitDeploymentPhase_ServiceUnitDeploymentPhase `protobuf:"varint,1,opt,name=phase,proto3,enum=blanketops.common.v1.ServiceUnitDeploymentPhase_ServiceUnitDeploymentPhase" json:"phase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceUnitDeploymentPhase) Reset() {
	*x = ServiceUnitDeploymentPhase{}
	mi := &file_blanketops_common_v1_serviceunit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceUnitDeploymentPhase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceUnitDeploymentPhase) ProtoMessage() {}

func (x *ServiceUnitDeploymentPhase) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_common_v1_serviceunit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceUnitDeploymentPhase.ProtoReflect.Descriptor instead.
func (*ServiceUnitDeploymentPhase) Descriptor() ([]byte, []int) {
	return file_blanketops_common_v1_serviceunit_proto_rawDescGZIP(), []int{0}
}

func (x *ServiceUnitDeploymentPhase) GetPhase() ServiceUnitDeploymentPhase_ServiceUnitDeploymentPhase {
	if x != nil {
		return x.Phase
	}
	return ServiceUnitDeploymentPhase_SERVICE_UNIT_DEPLOYMENT_PHASE_UNSPECIFIED
}

type ServiceUnitType struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Type          ServiceUnitType_ServiceUnitType `protobuf:"varint,1,opt,name=type,proto3,enum=blanketops.common.v1.ServiceUnitType_ServiceUnitType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceUnitType) Reset() {
	*x = ServiceUnitType{}
	mi := &file_blanketops_common_v1_serviceunit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceUnitType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceUnitType) ProtoMessage() {}

func (x *ServiceUnitType) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_common_v1_serviceunit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceUnitType.ProtoReflect.Descriptor instead.
func (*ServiceUnitType) Descriptor() ([]byte, []int) {
	return file_blanketops_common_v1_serviceunit_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceUnitType) GetType() ServiceUnitType_ServiceUnitType {
	if x != nil {
		return x.Type
	}
	return ServiceUnitType_SERVICE_UNIT_TYPE_UNSPECIFIED
}

type ServiceUnitRuntime struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Runtime       ServiceUnitRuntime_ServiceUnitRuntime `protobuf:"varint,1,opt,name=runtime,proto3,enum=blanketops.common.v1.ServiceUnitRuntime_ServiceUnitRuntime" json:"runtime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceUnitRuntime) Reset() {
	*x = ServiceUnitRuntime{}
	mi := &file_blanketops_common_v1_serviceunit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceUnitRuntime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceUnitRuntime) ProtoMessage() {}

func (x *ServiceUnitRuntime) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_common_v1_serviceunit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceUnitRuntime.ProtoReflect.Descriptor instead.
func (*ServiceUnitRuntime) Descriptor() ([]byte, []int) {
	return file_blanketops_common_v1_serviceunit_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceUnitRuntime) GetRuntime() ServiceUnitRuntime_ServiceUnitRuntime {
	if x != nil {
		return x.Runtime
	}
	return ServiceUnitRuntime_SERVICE_UNIT_RUNTIME_UNSPECIFIED
}

var File_blanketops_common_v1_serviceunit_proto protoreflect.FileDescriptor

const file_blanketops_common_v1_serviceunit_proto_rawDesc = "" +
	"\n" +
	"&blanketops/common/v1/serviceunit.proto\x12\x14blanketops.common.v1\"\xf8\x02\n" +
	"\x1aServiceUnitDeploymentPhase\x12a\n" +
	"\x05phase\x18\x01 \x01(\x0e2K.blanketops.common.v1.ServiceUnitDeploymentPhase.ServiceUnitDeploymentPhaseR\x05phase\"\xf6\x01\n" +
	"\x1aServiceUnitDeploymentPhase\x12-\n" +
	")SERVICE_UNIT_DEPLOYMENT_PHASE_UNSPECIFIED\x10\x00\x12)\n" +
	"%SERVICE_UNIT_DEPLOYMENT_PHASE_PENDING\x10\x01\x12+\n" +
	"'SERVICE_UNIT_DEPLOYMENT_PHASE_DEPLOYING\x10\x02\x12'\n" +
	"#SERVICE_UNIT_DEPLOYMENT_PHASE_READY\x10\x03\x12(\n" +
	"$SERVICE_UNIT_DEPLOYMENT_PHASE_FAILED\x10\x04\"\xf1\x01\n" +
	"\x0fServiceUnitType\x12I\n" +
	"\x04type\x18\x01 \x01(\x0e25.blanketops.common.v1.ServiceUnitType.ServiceUnitTypeR\x04type\"\x92\x01\n" +
	"\x0fServiceUnitType\x12!\n" +
	"\x1dSERVICE_UNIT_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18SERVICE_UNIT_TYPE_STATIC\x10\x01\x12\x1b\n" +
	"\x17SERVICE_UNIT_TYPE_BUILD\x10\x02\x12!\n" +
	"\x1dSERVICE_UNIT_TYPE_SUPPLYCHAIN\x10\x03\"\xac\x02\n" +
	"\x12ServiceUnitRuntime\x12U\n" +
	"\aruntime\x18\x01 \x01(\x0e2;.blanketops.common.v1.ServiceUnitRuntime.ServiceUnitRuntimeR\aruntime\"\xbe\x01\n" +
	"\x12ServiceUnitRuntime\x12$\n" +
	" SERVICE_UNIT_RUNTIME_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fSERVICE_UNIT_RUNTIME_KUBERNETES\x10\x01\x12 \n" +
	"\x1cSERVICE_UNIT_RUNTIME_KNATIVE\x10\x02\x12\x1c\n" +
	"\x18SERVICE_UNIT_RUNTIME_ECS\x10\x03\x12\x1d\n" +
	"\x19SERVICE_UNIT_RUNTIME_WASM\x10\x04BbZIgithub.com/blanketops/environments-contract/blanketops/common/v1;commonv1\xaa\x02\x14BlanketOps.Common.v1b\x06proto3"

var (
	file_blanketops_common_v1_serviceunit_proto_rawDescOnce sync.Once
	file_blanketops_common_v1_serviceunit_proto_rawDescData []byte
)

func file_blanketops_common_v1_serviceunit_proto_rawDescGZIP() []byte {
	file_blanketops_common_v1_serviceunit_proto_rawDescOnce.Do(func() {
		file_blanketops_common_v1_serviceunit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blanketops_common_v1_serviceunit_proto_rawDesc), len(file_blanketops_common_v1_serviceunit_proto_rawDesc)))
	})
	return file_blanketops_common_v1_serviceunit_proto_rawDescData
}

var file_blanketops_common_v1_serviceunit_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_blanketops_common_v1_serviceunit_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_blanketops_common_v1_serviceunit_proto_goTypes = []any{
	(ServiceUnitDeploymentPhase_ServiceUnitDeploymentPhase)(0), // 0: blanketops.common.v1.ServiceUnitDeploymentPhase.ServiceUnitDeploymentPhase
	(ServiceUnitType_ServiceUnitType)(0),                       // 1: blanketops.common.v1.ServiceUnitType.ServiceUnitType
	(ServiceUnitRuntime_ServiceUnitRuntime)(0),                 // 2: blanketops.common.v1.ServiceUnitRuntime.ServiceUnitRuntime
	(*ServiceUnitDeploymentPhase)(nil),                         // 3: blanketops.common.v1.ServiceUnitDeploymentPhase
	(*ServiceUnitType)(nil),                                    // 4: blanketops.common.v1.ServiceUnitType
	(*ServiceUnitRuntime)(nil),                                 // 5: blanketops.common.v1.ServiceUnitRuntime
}
var file_blanketops_common_v1_serviceunit_proto_depIdxs = []int32{
	0, // 0: blanketops.common.v1.ServiceUnitDeploymentPhase.phase:type_name -> blanketops.common.v1.ServiceUnitDeploymentPhase.ServiceUnitDeploymentPhase
	1, // 1: blanketops.common.v1.ServiceUnitType.type:type_name -> blanketops.common.v1.ServiceUnitType.ServiceUnitType
	2, // 2: blanketops.common.v1.ServiceUnitRuntime.runtime:type_name -> blanketops.common.v1.ServiceUnitRuntime.ServiceUnitRuntime
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_blanketops_common_v1_serviceunit_proto_init() }
func file_blanketops_common_v1_serviceunit_proto_init() {
	if File_blanketops_common_v1_serviceunit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blanketops_common_v1_serviceunit_proto_rawDesc), len(file_blanketops_common_v1_serviceunit_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blanketops_common_v1_serviceunit_proto_goTypes,
		DependencyIndexes: file_blanketops_common_v1_serviceunit_proto_depIdxs,
		EnumInfos:         file_blanketops_common_v1_serviceunit_proto_enumTypes,
		MessageInfos:      file_blanketops_common_v1_serviceunit_proto_msgTypes,
	}.Build()
	File_blanketops_common_v1_serviceunit_proto = out.File
	file_blanketops_common_v1_serviceunit_proto_goTypes = nil
	file_blanketops_common_v1_serviceunit_proto_depIdxs = nil
}
