//
// Copyright 2026 The BlanketOps Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// =============================================================================
// Domain
//
// Owns the cert/mapping chain for a host within a BlanketOps Environment.
//
// The controller materializes:
//   platform strategy → DomainClaim + DomainMapping
//   custom strategy   → Issuer + DomainClaim + DomainMapping + Certificate
//
// Owned by a Route CR via ownerReference (cascade delete).
// Route owns the workload binding (runtime, path, enabled).
// Domain owns the TLS chain and optional mTLS identity for the host.
//
// mTLS:
//   When spec.mtls.enforced is true, blanketops-proxy sidecars are injected
//   and blanketK issues identities for all workloads bound to this domain.
//   The platform wires the sidecar identity — no manual cert management needed.
//
// renewBefore:
//   Applies only to custom strategy. Controls cert-manager's renewal window.
//   Platform wildcard certs are renewed on the platform schedule regardless.
//
// Status refs:
//   status.certificate_ref  — set by controller on custom strategy; used by
//                             the Route mediator to gate DomainMapping dispatch
//                             without deriving the TLS secret name externally.
//   status.domain_mapping_ref — set once DomainMapping is materialized.
//
// APIVersion: networks.blanketops.dev/v1alpha1
// =============================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: blanketops/networks/v1alpha1/domain.proto

package v1alpha1

import (
	v1 "github.com/BlanketOps/environments-contract/blanketops/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Domain struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Standard BlanketOps metadata (name, namespace, labels, ownerRef).
	Metadata *v1.Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Desired state declared by the operator.
	Spec *DomainSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	// Observed state set by the controller. Never manually edited.
	Status        *DomainStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Domain) Reset() {
	*x = Domain{}
	mi := &file_blanketops_networks_v1alpha1_domain_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1alpha1_domain_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1alpha1_domain_proto_rawDescGZIP(), []int{0}
}

func (x *Domain) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Domain) GetSpec() *DomainSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Domain) GetStatus() *DomainStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type DomainSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fully qualified domain name this assignment covers.
	// platform strategy: must match the platform wildcard pattern (e.g. *.dev.domain.co.za)
	// custom strategy:   client-owned zone, any FQDN.
	Host string `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	// RouteRef is the Route in the same namespace that owns this Domain.
	// Route owns the workload binding (runtime, path, enabled).
	// Domain is cascade-deleted when the owning Route is deleted.
	RouteRef *DomainRouteRef `protobuf:"bytes,2,opt,name=route_ref,json=routeRef,proto3" json:"route_ref,omitempty"`
	// TlsStrategy controls which cert provisioning path the controller takes.
	// platform: platform wildcard cert already covers this host — DomainClaim + DomainMapping only.
	// custom:   client-owned zone — Issuer + DomainClaim + DomainMapping + Certificate.
	TlsStrategy *v1.DomainTLSStrategy `protobuf:"bytes,3,opt,name=tls_strategy,json=tlsStrategy,proto3" json:"tls_strategy,omitempty"`
	// Mtls configures inter-service mTLS for this domain.
	// When enforced, blanketops-proxy sidecars are injected and blanketK issues identities.
	// Absent or not enforced means plain TLS only.
	Mtls *DomainMTLS `protobuf:"bytes,4,opt,name=mtls,proto3" json:"mtls,omitempty"`
	// RenewBefore is the cert renewal window (e.g. "720h").
	// Applies to custom strategy only — platform wildcard certs use the platform schedule.
	// Empty string means cert-manager default applies.
	RenewBefore   string `protobuf:"bytes,5,opt,name=renew_before,json=renewBefore,proto3" json:"renew_before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainSpec) Reset() {
	*x = DomainSpec{}
	mi := &file_blanketops_networks_v1alpha1_domain_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainSpec) ProtoMessage() {}

func (x *DomainSpec) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1alpha1_domain_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainSpec.ProtoReflect.Descriptor instead.
func (*DomainSpec) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1alpha1_domain_proto_rawDescGZIP(), []int{1}
}

func (x *DomainSpec) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *DomainSpec) GetRouteRef() *DomainRouteRef {
	if x != nil {
		return x.RouteRef
	}
	return nil
}

func (x *DomainSpec) GetTlsStrategy() *v1.DomainTLSStrategy {
	if x != nil {
		return x.TlsStrategy
	}
	return nil
}

func (x *DomainSpec) GetMtls() *DomainMTLS {
	if x != nil {
		return x.Mtls
	}
	return nil
}

func (x *DomainSpec) GetRenewBefore() string {
	if x != nil {
		return x.RenewBefore
	}
	return ""
}

// DomainRouteRef identifies the Route CR that owns this Domain.
// Domain and Route must be in the same namespace.
type DomainRouteRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name is the Route CR name in the same namespace as this Domain.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainRouteRef) Reset() {
	*x = DomainRouteRef{}
	mi := &file_blanketops_networks_v1alpha1_domain_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainRouteRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainRouteRef) ProtoMessage() {}

func (x *DomainRouteRef) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1alpha1_domain_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainRouteRef.ProtoReflect.Descriptor instead.
func (*DomainRouteRef) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1alpha1_domain_proto_rawDescGZIP(), []int{2}
}

func (x *DomainRouteRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// DomainMTLS configures inter-service mTLS for this domain.
type DomainMTLS struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Enforced controls whether blanketops-proxy + blanketK mTLS is active.
	// When true, the platform wires sidecar identity automatically.
	Enforced      bool `protobuf:"varint,1,opt,name=enforced,proto3" json:"enforced,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainMTLS) Reset() {
	*x = DomainMTLS{}
	mi := &file_blanketops_networks_v1alpha1_domain_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainMTLS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainMTLS) ProtoMessage() {}

func (x *DomainMTLS) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1alpha1_domain_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainMTLS.ProtoReflect.Descriptor instead.
func (*DomainMTLS) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1alpha1_domain_proto_rawDescGZIP(), []int{3}
}

func (x *DomainMTLS) GetEnforced() bool {
	if x != nil {
		return x.Enforced
	}
	return false
}

// DomainObjectRef is a namespaced reference to a Kubernetes resource
// materialized by the Domain controller (Certificate, DomainMapping).
// Set in status once the resource is created — never in spec.
type DomainObjectRef struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the referenced resource.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Namespace of the referenced resource.
	// For DomainMapping: same namespace as this Domain.
	// For Certificate:   same namespace as this Domain.
	Namespace     string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainObjectRef) Reset() {
	*x = DomainObjectRef{}
	mi := &file_blanketops_networks_v1alpha1_domain_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainObjectRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainObjectRef) ProtoMessage() {}

func (x *DomainObjectRef) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1alpha1_domain_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainObjectRef.ProtoReflect.Descriptor instead.
func (*DomainObjectRef) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1alpha1_domain_proto_rawDescGZIP(), []int{4}
}

func (x *DomainObjectRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DomainObjectRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type DomainStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current lifecycle phase. Set by the controller.
	Phase *v1.DomainPhase `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	// Human-readable status message. Populated on failure or provisioning.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// CertIssued is true once a valid TLS certificate has been issued for this host.
	// Always true for platform strategy once DomainMapping is active.
	// Tracks cert-manager issuance for custom strategy.
	CertIssued bool `protobuf:"varint,3,opt,name=cert_issued,json=certIssued,proto3" json:"cert_issued,omitempty"`
	// TlsStatus is the current TLS provisioning state.
	TlsStatus *v1.DomainTLSStatus `protobuf:"bytes,4,opt,name=tls_status,json=tlsStatus,proto3" json:"tls_status,omitempty"`
	// Conditions for UI and automation consumers.
	Conditions []*DomainCondition `protobuf:"bytes,5,rep,name=conditions,proto3" json:"conditions,omitempty"`
	// LastUpdatedAt is when the controller last wrote to this status.
	LastUpdatedAt *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=last_updated_at,json=lastUpdatedAt,proto3" json:"last_updated_at,omitempty"`
	// DomainReady is true when both DomainClaim and DomainMapping are
	// reconciled and active. Mirrors the DomainMappingReady condition
	// as a scalar for fast consumer reads.
	DomainReady bool `protobuf:"varint,7,opt,name=domain_ready,json=domainReady,proto3" json:"domain_ready,omitempty"`
	// CertificateRef is the Certificate resource emitted by the controller.
	// Set only when tls_strategy is custom — empty for platform strategy.
	// The Route mediator reads this ref to gate DomainMapping dispatch
	// on TLS secret existence without deriving the secret name externally.
	CertificateRef *DomainObjectRef `protobuf:"bytes,8,opt,name=certificate_ref,json=certificateRef,proto3" json:"certificate_ref,omitempty"`
	// DomainMappingRef is the Knative DomainMapping resource emitted
	// by the controller. Set once materialized, cleared on deletion.
	DomainMappingRef *DomainObjectRef `protobuf:"bytes,9,opt,name=domain_mapping_ref,json=domainMappingRef,proto3" json:"domain_mapping_ref,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DomainStatus) Reset() {
	*x = DomainStatus{}
	mi := &file_blanketops_networks_v1alpha1_domain_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainStatus) ProtoMessage() {}

func (x *DomainStatus) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1alpha1_domain_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainStatus.ProtoReflect.Descriptor instead.
func (*DomainStatus) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1alpha1_domain_proto_rawDescGZIP(), []int{5}
}

func (x *DomainStatus) GetPhase() *v1.DomainPhase {
	if x != nil {
		return x.Phase
	}
	return nil
}

func (x *DomainStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DomainStatus) GetCertIssued() bool {
	if x != nil {
		return x.CertIssued
	}
	return false
}

func (x *DomainStatus) GetTlsStatus() *v1.DomainTLSStatus {
	if x != nil {
		return x.TlsStatus
	}
	return nil
}

func (x *DomainStatus) GetConditions() []*DomainCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *DomainStatus) GetLastUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUpdatedAt
	}
	return nil
}

func (x *DomainStatus) GetDomainReady() bool {
	if x != nil {
		return x.DomainReady
	}
	return false
}

func (x *DomainStatus) GetCertificateRef() *DomainObjectRef {
	if x != nil {
		return x.CertificateRef
	}
	return nil
}

func (x *DomainStatus) GetDomainMappingRef() *DomainObjectRef {
	if x != nil {
		return x.DomainMappingRef
	}
	return nil
}

type DomainCondition struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Condition type. e.g. DomainResolved, CertIssued, MTLSReady, DomainMappingReady
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Condition status: True, False, or Unknown.
	Status string `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	// Machine-readable reason for the last transition.
	Reason        string `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DomainCondition) Reset() {
	*x = DomainCondition{}
	mi := &file_blanketops_networks_v1alpha1_domain_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainCondition) ProtoMessage() {}

func (x *DomainCondition) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_networks_v1alpha1_domain_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DomainCondition.ProtoReflect.Descriptor instead.
func (*DomainCondition) Descriptor() ([]byte, []int) {
	return file_blanketops_networks_v1alpha1_domain_proto_rawDescGZIP(), []int{6}
}

func (x *DomainCondition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DomainCondition) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DomainCondition) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

var File_blanketops_networks_v1alpha1_domain_proto protoreflect.FileDescriptor

const file_blanketops_networks_v1alpha1_domain_proto_rawDesc = "" +
	"\n" +
	")blanketops/networks/v1alpha1/domain.proto\x12\x1cblanketops.networks.v1alpha1\x1a!blanketops/common/v1/domain.proto\x1a#blanketops/common/v1/metadata.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\x01\n" +
	"\x06Domain\x12:\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1e.blanketops.common.v1.MetadataR\bmetadata\x12<\n" +
	"\x04spec\x18\x02 \x01(\v2(.blanketops.networks.v1alpha1.DomainSpecR\x04spec\x12B\n" +
	"\x06status\x18\x03 \x01(\v2*.blanketops.networks.v1alpha1.DomainStatusR\x06status\"\x98\x02\n" +
	"\n" +
	"DomainSpec\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12I\n" +
	"\troute_ref\x18\x02 \x01(\v2,.blanketops.networks.v1alpha1.DomainRouteRefR\brouteRef\x12J\n" +
	"\ftls_strategy\x18\x03 \x01(\v2'.blanketops.common.v1.DomainTLSStrategyR\vtlsStrategy\x12<\n" +
	"\x04mtls\x18\x04 \x01(\v2(.blanketops.networks.v1alpha1.DomainMTLSR\x04mtls\x12!\n" +
	"\frenew_before\x18\x05 \x01(\tR\vrenewBefore\"$\n" +
	"\x0eDomainRouteRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"(\n" +
	"\n" +
	"DomainMTLS\x12\x1a\n" +
	"\benforced\x18\x01 \x01(\bR\benforced\"C\n" +
	"\x0fDomainObjectRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\"\xb3\x04\n" +
	"\fDomainStatus\x127\n" +
	"\x05phase\x18\x01 \x01(\v2!.blanketops.common.v1.DomainPhaseR\x05phase\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vcert_issued\x18\x03 \x01(\bR\n" +
	"certIssued\x12D\n" +
	"\n" +
	"tls_status\x18\x04 \x01(\v2%.blanketops.common.v1.DomainTLSStatusR\ttlsStatus\x12M\n" +
	"\n" +
	"conditions\x18\x05 \x03(\v2-.blanketops.networks.v1alpha1.DomainConditionR\n" +
	"conditions\x12B\n" +
	"\x0flast_updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rlastUpdatedAt\x12!\n" +
	"\fdomain_ready\x18\a \x01(\bR\vdomainReady\x12V\n" +
	"\x0fcertificate_ref\x18\b \x01(\v2-.blanketops.networks.v1alpha1.DomainObjectRefR\x0ecertificateRef\x12[\n" +
	"\x12domain_mapping_ref\x18\t \x01(\v2-.blanketops.networks.v1alpha1.DomainObjectRefR\x10domainMappingRef\"U\n" +
	"\x0fDomainCondition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reasonB\x9d\x01\n" +
	"\x1cv1alpha1.networks.blanketopsB\vDomainProtoZQgithub.com/BlanketOps/environments-contract/blanketops/networks/v1alpha1;v1alpha1\xaa\x02\x1cBlanketOps.Networks.v1Alpha1b\x06proto3"

var (
	file_blanketops_networks_v1alpha1_domain_proto_rawDescOnce sync.Once
	file_blanketops_networks_v1alpha1_domain_proto_rawDescData []byte
)

func file_blanketops_networks_v1alpha1_domain_proto_rawDescGZIP() []byte {
	file_blanketops_networks_v1alpha1_domain_proto_rawDescOnce.Do(func() {
		file_blanketops_networks_v1alpha1_domain_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blanketops_networks_v1alpha1_domain_proto_rawDesc), len(file_blanketops_networks_v1alpha1_domain_proto_rawDesc)))
	})
	return file_blanketops_networks_v1alpha1_domain_proto_rawDescData
}

var file_blanketops_networks_v1alpha1_domain_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_blanketops_networks_v1alpha1_domain_proto_goTypes = []any{
	(*Domain)(nil),                // 0: blanketops.networks.v1alpha1.Domain
	(*DomainSpec)(nil),            // 1: blanketops.networks.v1alpha1.DomainSpec
	(*DomainRouteRef)(nil),        // 2: blanketops.networks.v1alpha1.DomainRouteRef
	(*DomainMTLS)(nil),            // 3: blanketops.networks.v1alpha1.DomainMTLS
	(*DomainObjectRef)(nil),       // 4: blanketops.networks.v1alpha1.DomainObjectRef
	(*DomainStatus)(nil),          // 5: blanketops.networks.v1alpha1.DomainStatus
	(*DomainCondition)(nil),       // 6: blanketops.networks.v1alpha1.DomainCondition
	(*v1.Metadata)(nil),           // 7: blanketops.common.v1.Metadata
	(*v1.DomainTLSStrategy)(nil),  // 8: blanketops.common.v1.DomainTLSStrategy
	(*v1.DomainPhase)(nil),        // 9: blanketops.common.v1.DomainPhase
	(*v1.DomainTLSStatus)(nil),    // 10: blanketops.common.v1.DomainTLSStatus
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_blanketops_networks_v1alpha1_domain_proto_depIdxs = []int32{
	7,  // 0: blanketops.networks.v1alpha1.Domain.metadata:type_name -> blanketops.common.v1.Metadata
	1,  // 1: blanketops.networks.v1alpha1.Domain.spec:type_name -> blanketops.networks.v1alpha1.DomainSpec
	5,  // 2: blanketops.networks.v1alpha1.Domain.status:type_name -> blanketops.networks.v1alpha1.DomainStatus
	2,  // 3: blanketops.networks.v1alpha1.DomainSpec.route_ref:type_name -> blanketops.networks.v1alpha1.DomainRouteRef
	8,  // 4: blanketops.networks.v1alpha1.DomainSpec.tls_strategy:type_name -> blanketops.common.v1.DomainTLSStrategy
	3,  // 5: blanketops.networks.v1alpha1.DomainSpec.mtls:type_name -> blanketops.networks.v1alpha1.DomainMTLS
	9,  // 6: blanketops.networks.v1alpha1.DomainStatus.phase:type_name -> blanketops.common.v1.DomainPhase
	10, // 7: blanketops.networks.v1alpha1.DomainStatus.tls_status:type_name -> blanketops.common.v1.DomainTLSStatus
	6,  // 8: blanketops.networks.v1alpha1.DomainStatus.conditions:type_name -> blanketops.networks.v1alpha1.DomainCondition
	11, // 9: blanketops.networks.v1alpha1.DomainStatus.last_updated_at:type_name -> google.protobuf.Timestamp
	4,  // 10: blanketops.networks.v1alpha1.DomainStatus.certificate_ref:type_name -> blanketops.networks.v1alpha1.DomainObjectRef
	4,  // 11: blanketops.networks.v1alpha1.DomainStatus.domain_mapping_ref:type_name -> blanketops.networks.v1alpha1.DomainObjectRef
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_blanketops_networks_v1alpha1_domain_proto_init() }
func file_blanketops_networks_v1alpha1_domain_proto_init() {
	if File_blanketops_networks_v1alpha1_domain_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blanketops_networks_v1alpha1_domain_proto_rawDesc), len(file_blanketops_networks_v1alpha1_domain_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blanketops_networks_v1alpha1_domain_proto_goTypes,
		DependencyIndexes: file_blanketops_networks_v1alpha1_domain_proto_depIdxs,
		MessageInfos:      file_blanketops_networks_v1alpha1_domain_proto_msgTypes,
	}.Build()
	File_blanketops_networks_v1alpha1_domain_proto = out.File
	file_blanketops_networks_v1alpha1_domain_proto_goTypes = nil
	file_blanketops_networks_v1alpha1_domain_proto_depIdxs = nil
}
