//
// Copyright 2026 The BlanketOps Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// =============================================================================
// Domain
//
// Owns the cert/mapping chain for a host within a BlanketOps Environment.
//
// The controller materializes:
//   platform strategy → DomainClaim + DomainMapping
//   custom strategy   → Issuer + DomainClaim + DomainMapping + Certificate
//
// Owned by a Route CR via ownerReference (cascade delete).
// Route owns the workload binding (runtime, path, enabled).
// Domain owns the TLS chain and optional mTLS identity for the host.
//
// mTLS:
//   When spec.mtls.enforced is true, blanketops-proxy sidecars are injected
//   and blanketK issues identities for all workloads bound to this domain.
//   The platform wires the sidecar identity — no manual cert management needed.
//
// renewBefore:
//   Applies only to custom strategy. Controls cert-manager's renewal window.
//   Platform wildcard certs are renewed on the platform schedule regardless.
//
// Status refs:
//   status.certificate_ref  — set by controller on custom strategy; used by
//                             the Route mediator to gate DomainMapping dispatch
//                             without deriving the TLS secret name externally.
//   status.domain_mapping_ref — set once DomainMapping is materialized.
//
// APIVersion: networks.blanketops.dev/v1alpha1
// =============================================================================

// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=none"
// @generated from file blanketops/networks/v1alpha1/domain.proto (package blanketops.networks.v1alpha1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { DomainPhase, DomainTLSStatus, DomainTLSStrategy } from "../../common/v1/domain_pb";
import { file_blanketops_common_v1_domain } from "../../common/v1/domain_pb";
import type { Metadata } from "../../common/v1/metadata_pb";
import { file_blanketops_common_v1_metadata } from "../../common/v1/metadata_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file blanketops/networks/v1alpha1/domain.proto.
 */
export const file_blanketops_networks_v1alpha1_domain: GenFile = /*@__PURE__*/
  fileDesc("CilibGFua2V0b3BzL25ldHdvcmtzL3YxYWxwaGExL2RvbWFpbi5wcm90bxIcYmxhbmtldG9wcy5uZXR3b3Jrcy52MWFscGhhMSKuAQoGRG9tYWluEjAKCG1ldGFkYXRhGAEgASgLMh4uYmxhbmtldG9wcy5jb21tb24udjEuTWV0YWRhdGESNgoEc3BlYxgCIAEoCzIoLmJsYW5rZXRvcHMubmV0d29ya3MudjFhbHBoYTEuRG9tYWluU3BlYxI6CgZzdGF0dXMYAyABKAsyKi5ibGFua2V0b3BzLm5ldHdvcmtzLnYxYWxwaGExLkRvbWFpblN0YXR1cyLoAQoKRG9tYWluU3BlYxIMCgRob3N0GAEgASgJEj8KCXJvdXRlX3JlZhgCIAEoCzIsLmJsYW5rZXRvcHMubmV0d29ya3MudjFhbHBoYTEuRG9tYWluUm91dGVSZWYSPQoMdGxzX3N0cmF0ZWd5GAMgASgLMicuYmxhbmtldG9wcy5jb21tb24udjEuRG9tYWluVExTU3RyYXRlZ3kSNgoEbXRscxgEIAEoCzIoLmJsYW5rZXRvcHMubmV0d29ya3MudjFhbHBoYTEuRG9tYWluTVRMUxIUCgxyZW5ld19iZWZvcmUYBSABKAkiHgoORG9tYWluUm91dGVSZWYSDAoEbmFtZRgBIAEoCSIeCgpEb21haW5NVExTEhAKCGVuZm9yY2VkGAEgASgIIjIKD0RvbWFpbk9iamVjdFJlZhIMCgRuYW1lGAEgASgJEhEKCW5hbWVzcGFjZRgCIAEoCSLCAwoMRG9tYWluU3RhdHVzEjAKBXBoYXNlGAEgASgLMiEuYmxhbmtldG9wcy5jb21tb24udjEuRG9tYWluUGhhc2USDwoHbWVzc2FnZRgCIAEoCRITCgtjZXJ0X2lzc3VlZBgDIAEoCBI5Cgp0bHNfc3RhdHVzGAQgASgLMiUuYmxhbmtldG9wcy5jb21tb24udjEuRG9tYWluVExTU3RhdHVzEkEKCmNvbmRpdGlvbnMYBSADKAsyLS5ibGFua2V0b3BzLm5ldHdvcmtzLnYxYWxwaGExLkRvbWFpbkNvbmRpdGlvbhIzCg9sYXN0X3VwZGF0ZWRfYXQYBiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEhQKDGRvbWFpbl9yZWFkeRgHIAEoCBJGCg9jZXJ0aWZpY2F0ZV9yZWYYCCABKAsyLS5ibGFua2V0b3BzLm5ldHdvcmtzLnYxYWxwaGExLkRvbWFpbk9iamVjdFJlZhJJChJkb21haW5fbWFwcGluZ19yZWYYCSABKAsyLS5ibGFua2V0b3BzLm5ldHdvcmtzLnYxYWxwaGExLkRvbWFpbk9iamVjdFJlZiI/Cg9Eb21haW5Db25kaXRpb24SDAoEdHlwZRgBIAEoCRIOCgZzdGF0dXMYAiABKAkSDgoGcmVhc29uGAMgASgJQqkBChx2MWFscGhhMS5uZXR3b3Jrcy5ibGFua2V0b3BzQgtEb21haW5Qcm90b1pdZ2l0aHViLmNvbS9udGxhbGV0c2k3MC9ibGFua2V0b3BzLWVudmlyb25tZW50cy1jb250cmFjdC9ibGFua2V0b3BzL25ldHdvcmtzL3YxYWxwaGExO3YxYWxwaGExqgIcQmxhbmtldE9wcy5OZXR3b3Jrcy52MUFscGhhMWIGcHJvdG8z", [file_blanketops_common_v1_domain, file_blanketops_common_v1_metadata, file_google_protobuf_timestamp]);

/**
 * @generated from message blanketops.networks.v1alpha1.Domain
 */
export type Domain = Message<"blanketops.networks.v1alpha1.Domain"> & {
  /**
   * Standard BlanketOps metadata (name, namespace, labels, ownerRef).
   *
   * @generated from field: blanketops.common.v1.Metadata metadata = 1;
   */
  metadata?: Metadata | undefined;

  /**
   * Desired state declared by the operator.
   *
   * @generated from field: blanketops.networks.v1alpha1.DomainSpec spec = 2;
   */
  spec?: DomainSpec | undefined;

  /**
   * Observed state set by the controller. Never manually edited.
   *
   * @generated from field: blanketops.networks.v1alpha1.DomainStatus status = 3;
   */
  status?: DomainStatus | undefined;
};

/**
 * Describes the message blanketops.networks.v1alpha1.Domain.
 * Use `create(DomainSchema)` to create a new message.
 */
export const DomainSchema: GenMessage<Domain> = /*@__PURE__*/
  messageDesc(file_blanketops_networks_v1alpha1_domain, 0);

/**
 * @generated from message blanketops.networks.v1alpha1.DomainSpec
 */
export type DomainSpec = Message<"blanketops.networks.v1alpha1.DomainSpec"> & {
  /**
   * Fully qualified domain name this assignment covers.
   * platform strategy: must match the platform wildcard pattern (e.g. *.dev.domain.co.za)
   * custom strategy:   client-owned zone, any FQDN.
   *
   * @generated from field: string host = 1;
   */
  host: string;

  /**
   * RouteRef is the Route in the same namespace that owns this Domain.
   * Route owns the workload binding (runtime, path, enabled).
   * Domain is cascade-deleted when the owning Route is deleted.
   *
   * @generated from field: blanketops.networks.v1alpha1.DomainRouteRef route_ref = 2;
   */
  routeRef?: DomainRouteRef | undefined;

  /**
   * TlsStrategy controls which cert provisioning path the controller takes.
   * platform: platform wildcard cert already covers this host — DomainClaim + DomainMapping only.
   * custom:   client-owned zone — Issuer + DomainClaim + DomainMapping + Certificate.
   *
   * @generated from field: blanketops.common.v1.DomainTLSStrategy tls_strategy = 3;
   */
  tlsStrategy?: DomainTLSStrategy | undefined;

  /**
   * Mtls configures inter-service mTLS for this domain.
   * When enforced, blanketops-proxy sidecars are injected and blanketK issues identities.
   * Absent or not enforced means plain TLS only.
   *
   * @generated from field: blanketops.networks.v1alpha1.DomainMTLS mtls = 4;
   */
  mtls?: DomainMTLS | undefined;

  /**
   * RenewBefore is the cert renewal window (e.g. "720h").
   * Applies to custom strategy only — platform wildcard certs use the platform schedule.
   * Empty string means cert-manager default applies.
   *
   * @generated from field: string renew_before = 5;
   */
  renewBefore: string;
};

/**
 * Describes the message blanketops.networks.v1alpha1.DomainSpec.
 * Use `create(DomainSpecSchema)` to create a new message.
 */
export const DomainSpecSchema: GenMessage<DomainSpec> = /*@__PURE__*/
  messageDesc(file_blanketops_networks_v1alpha1_domain, 1);

/**
 * DomainRouteRef identifies the Route CR that owns this Domain.
 * Domain and Route must be in the same namespace.
 *
 * @generated from message blanketops.networks.v1alpha1.DomainRouteRef
 */
export type DomainRouteRef = Message<"blanketops.networks.v1alpha1.DomainRouteRef"> & {
  /**
   * Name is the Route CR name in the same namespace as this Domain.
   *
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message blanketops.networks.v1alpha1.DomainRouteRef.
 * Use `create(DomainRouteRefSchema)` to create a new message.
 */
export const DomainRouteRefSchema: GenMessage<DomainRouteRef> = /*@__PURE__*/
  messageDesc(file_blanketops_networks_v1alpha1_domain, 2);

/**
 * DomainMTLS configures inter-service mTLS for this domain.
 *
 * @generated from message blanketops.networks.v1alpha1.DomainMTLS
 */
export type DomainMTLS = Message<"blanketops.networks.v1alpha1.DomainMTLS"> & {
  /**
   * Enforced controls whether blanketops-proxy + blanketK mTLS is active.
   * When true, the platform wires sidecar identity automatically.
   *
   * @generated from field: bool enforced = 1;
   */
  enforced: boolean;
};

/**
 * Describes the message blanketops.networks.v1alpha1.DomainMTLS.
 * Use `create(DomainMTLSSchema)` to create a new message.
 */
export const DomainMTLSSchema: GenMessage<DomainMTLS> = /*@__PURE__*/
  messageDesc(file_blanketops_networks_v1alpha1_domain, 3);

/**
 * DomainObjectRef is a namespaced reference to a Kubernetes resource
 * materialized by the Domain controller (Certificate, DomainMapping).
 * Set in status once the resource is created — never in spec.
 *
 * @generated from message blanketops.networks.v1alpha1.DomainObjectRef
 */
export type DomainObjectRef = Message<"blanketops.networks.v1alpha1.DomainObjectRef"> & {
  /**
   * Name of the referenced resource.
   *
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * Namespace of the referenced resource.
   * For DomainMapping: same namespace as this Domain.
   * For Certificate:   same namespace as this Domain.
   *
   * @generated from field: string namespace = 2;
   */
  namespace: string;
};

/**
 * Describes the message blanketops.networks.v1alpha1.DomainObjectRef.
 * Use `create(DomainObjectRefSchema)` to create a new message.
 */
export const DomainObjectRefSchema: GenMessage<DomainObjectRef> = /*@__PURE__*/
  messageDesc(file_blanketops_networks_v1alpha1_domain, 4);

/**
 * @generated from message blanketops.networks.v1alpha1.DomainStatus
 */
export type DomainStatus = Message<"blanketops.networks.v1alpha1.DomainStatus"> & {
  /**
   * Current lifecycle phase. Set by the controller.
   *
   * @generated from field: blanketops.common.v1.DomainPhase phase = 1;
   */
  phase?: DomainPhase | undefined;

  /**
   * Human-readable status message. Populated on failure or provisioning.
   *
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * CertIssued is true once a valid TLS certificate has been issued for this host.
   * Always true for platform strategy once DomainMapping is active.
   * Tracks cert-manager issuance for custom strategy.
   *
   * @generated from field: bool cert_issued = 3;
   */
  certIssued: boolean;

  /**
   * TlsStatus is the current TLS provisioning state.
   *
   * @generated from field: blanketops.common.v1.DomainTLSStatus tls_status = 4;
   */
  tlsStatus?: DomainTLSStatus | undefined;

  /**
   * Conditions for UI and automation consumers.
   *
   * @generated from field: repeated blanketops.networks.v1alpha1.DomainCondition conditions = 5;
   */
  conditions: DomainCondition[];

  /**
   * LastUpdatedAt is when the controller last wrote to this status.
   *
   * @generated from field: google.protobuf.Timestamp last_updated_at = 6;
   */
  lastUpdatedAt?: Timestamp | undefined;

  /**
   * DomainReady is true when both DomainClaim and DomainMapping are
   * reconciled and active. Mirrors the DomainMappingReady condition
   * as a scalar for fast consumer reads.
   *
   * @generated from field: bool domain_ready = 7;
   */
  domainReady: boolean;

  /**
   * CertificateRef is the Certificate resource emitted by the controller.
   * Set only when tls_strategy is custom — empty for platform strategy.
   * The Route mediator reads this ref to gate DomainMapping dispatch
   * on TLS secret existence without deriving the secret name externally.
   *
   * @generated from field: blanketops.networks.v1alpha1.DomainObjectRef certificate_ref = 8;
   */
  certificateRef?: DomainObjectRef | undefined;

  /**
   * DomainMappingRef is the Knative DomainMapping resource emitted
   * by the controller. Set once materialized, cleared on deletion.
   *
   * @generated from field: blanketops.networks.v1alpha1.DomainObjectRef domain_mapping_ref = 9;
   */
  domainMappingRef?: DomainObjectRef | undefined;
};

/**
 * Describes the message blanketops.networks.v1alpha1.DomainStatus.
 * Use `create(DomainStatusSchema)` to create a new message.
 */
export const DomainStatusSchema: GenMessage<DomainStatus> = /*@__PURE__*/
  messageDesc(file_blanketops_networks_v1alpha1_domain, 5);

/**
 * @generated from message blanketops.networks.v1alpha1.DomainCondition
 */
export type DomainCondition = Message<"blanketops.networks.v1alpha1.DomainCondition"> & {
  /**
   * Condition type. e.g. DomainResolved, CertIssued, MTLSReady, DomainMappingReady
   *
   * @generated from field: string type = 1;
   */
  type: string;

  /**
   * Condition status: True, False, or Unknown.
   *
   * @generated from field: string status = 2;
   */
  status: string;

  /**
   * Machine-readable reason for the last transition.
   *
   * @generated from field: string reason = 3;
   */
  reason: string;
};

/**
 * Describes the message blanketops.networks.v1alpha1.DomainCondition.
 * Use `create(DomainConditionSchema)` to create a new message.
 */
export const DomainConditionSchema: GenMessage<DomainCondition> = /*@__PURE__*/
  messageDesc(file_blanketops_networks_v1alpha1_domain, 6);

