//
//Copyright 2026 The BlanketOps Authors.
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: blanketops/environments/v1beta1/build.proto

package v1beta1

import (
	v1 "github.com/ntlaletsi70/blanketops-environments-contract/blanketops/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Build struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Standard BlanketOps metadata (name, namespace, labels, ownerRef).
	Metadata *v1.Metadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Desired state declared by the operator.
	Spec *BuildSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	// Observed state set by the controller. Never manually edited.
	Status        *BuildStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Build) Reset() {
	*x = Build{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Build) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Build) ProtoMessage() {}

func (x *Build) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Build.ProtoReflect.Descriptor instead.
func (*Build) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{0}
}

func (x *Build) GetMetadata() *v1.Metadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Build) GetSpec() *BuildSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Build) GetStatus() *BuildStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type BuildSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fully qualified target image — registry/repo/app:tag.
	// Tag strategy: git-sha, semver, or literal.
	// e.g. docker.io/nkanyezisolutions/for-kaniko-app:main
	Image string `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	// Shipwright ClusterBuildStrategy or namespaced BuildStrategy to use.
	Strategy *BuildStrategy `protobuf:"bytes,2,opt,name=strategy,proto3" json:"strategy,omitempty"`
	// Git source configuration — where to clone from.
	Source *GitSource `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// Trigger and retry policy for this build.
	Policy *BuildPolicy `protobuf:"bytes,4,opt,name=policy,proto3" json:"policy,omitempty"`
	// Kubernetes ServiceAccount used by the build pod.
	// Must have push access to the image registry.
	ServiceAccount *ServiceAccount `protobuf:"bytes,5,opt,name=service_account,json=serviceAccount,proto3" json:"service_account,omitempty"`
	// Additional parameters passed to the Shipwright BuildStrategy.
	// Merged with strategy defaults — these take precedence.
	Params []*Param `protobuf:"bytes,6,rep,name=params,proto3" json:"params,omitempty"`
	// Maximum duration a BuildRun may run before being cancelled.
	// Defaults to the strategy default if unset.
	Timeout *durationpb.Duration `protobuf:"bytes,7,opt,name=timeout,proto3" json:"timeout,omitempty"`
	// How long a completed BuildRun is retained before garbage collection.
	TimeToLive    *durationpb.Duration `protobuf:"bytes,8,opt,name=time_to_live,json=timeToLive,proto3" json:"time_to_live,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildSpec) Reset() {
	*x = BuildSpec{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildSpec) ProtoMessage() {}

func (x *BuildSpec) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildSpec.ProtoReflect.Descriptor instead.
func (*BuildSpec) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{1}
}

func (x *BuildSpec) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *BuildSpec) GetStrategy() *BuildStrategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

func (x *BuildSpec) GetSource() *GitSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *BuildSpec) GetPolicy() *BuildPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *BuildSpec) GetServiceAccount() *ServiceAccount {
	if x != nil {
		return x.ServiceAccount
	}
	return nil
}

func (x *BuildSpec) GetParams() []*Param {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *BuildSpec) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

func (x *BuildSpec) GetTimeToLive() *durationpb.Duration {
	if x != nil {
		return x.TimeToLive
	}
	return nil
}

type GitSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// SSH or HTTPS URL of the Git repository.
	// SSH format: git@github.com:<owner>/<repo>.git
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Branch, tag, or commit SHA to build from.
	// e.g. main, refs/heads/main, abc1234
	Revision string `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	// Path within the repository to use as the build context.
	// Required for kaniko strategy. Defaults to repository root.
	ContextDir string `protobuf:"bytes,3,opt,name=context_dir,json=contextDir,proto3" json:"context_dir,omitempty"`
	// Clone depth — 0 means full history.
	// Set to 1 for faster CI builds when history is not needed.
	Depth uint32 `protobuf:"varint,4,opt,name=depth,proto3" json:"depth,omitempty"`
	// Whether to verify the Git server TLS certificate.
	// Set to false only for internal Git servers with self-signed certs.
	SslVerify bool `protobuf:"varint,5,opt,name=ssl_verify,json=sslVerify,proto3" json:"ssl_verify,omitempty"`
	// Name of the Kubernetes Secret containing SSH private key.
	// Sourced from the environment SecretStore via ExternalSecret.
	// Key: ssh-privatekey
	CloneSecret   string `protobuf:"bytes,6,opt,name=clone_secret,json=cloneSecret,proto3" json:"clone_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitSource) Reset() {
	*x = GitSource{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitSource) ProtoMessage() {}

func (x *GitSource) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitSource.ProtoReflect.Descriptor instead.
func (*GitSource) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{2}
}

func (x *GitSource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GitSource) GetRevision() string {
	if x != nil {
		return x.Revision
	}
	return ""
}

func (x *GitSource) GetContextDir() string {
	if x != nil {
		return x.ContextDir
	}
	return ""
}

func (x *GitSource) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *GitSource) GetSslVerify() bool {
	if x != nil {
		return x.SslVerify
	}
	return false
}

func (x *GitSource) GetCloneSecret() string {
	if x != nil {
		return x.CloneSecret
	}
	return ""
}

type BuildStrategy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the Shipwright BuildStrategy.
	// Known values: kaniko | buildah-shipwright-managed-push | buildpacks-v3
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Scope of the strategy resource.
	Kind          *v1.BuildStrategyKind `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildStrategy) Reset() {
	*x = BuildStrategy{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildStrategy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildStrategy) ProtoMessage() {}

func (x *BuildStrategy) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildStrategy.ProtoReflect.Descriptor instead.
func (*BuildStrategy) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{3}
}

func (x *BuildStrategy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BuildStrategy) GetKind() *v1.BuildStrategyKind {
	if x != nil {
		return x.Kind
	}
	return nil
}

type BuildPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Events that are permitted to trigger a BuildRun.
	// At least one trigger must be specified.
	AllowedTriggers []*BuildTriggerPolicy `protobuf:"bytes,1,rep,name=allowed_triggers,json=allowedTriggers,proto3" json:"allowed_triggers,omitempty"`
	// Retry behaviour on BuildRun failure.
	Retry         *RetryPolicy `protobuf:"bytes,2,opt,name=retry,proto3" json:"retry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildPolicy) Reset() {
	*x = BuildPolicy{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildPolicy) ProtoMessage() {}

func (x *BuildPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildPolicy.ProtoReflect.Descriptor instead.
func (*BuildPolicy) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{4}
}

func (x *BuildPolicy) GetAllowedTriggers() []*BuildTriggerPolicy {
	if x != nil {
		return x.AllowedTriggers
	}
	return nil
}

func (x *BuildPolicy) GetRetry() *RetryPolicy {
	if x != nil {
		return x.Retry
	}
	return nil
}

type BuildTriggerPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The event type that permits a BuildRun to be triggered.
	Type          *v1.BuildTriggerType `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildTriggerPolicy) Reset() {
	*x = BuildTriggerPolicy{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildTriggerPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildTriggerPolicy) ProtoMessage() {}

func (x *BuildTriggerPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildTriggerPolicy.ProtoReflect.Descriptor instead.
func (*BuildTriggerPolicy) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{5}
}

func (x *BuildTriggerPolicy) GetType() *v1.BuildTriggerType {
	if x != nil {
		return x.Type
	}
	return nil
}

type RetryPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether to automatically retry a failed BuildRun.
	OnFailure bool `protobuf:"varint,1,opt,name=on_failure,json=onFailure,proto3" json:"on_failure,omitempty"`
	// Maximum number of retry attempts before marking the Build failed.
	MaxAttempts   uint32 `protobuf:"varint,2,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicy.ProtoReflect.Descriptor instead.
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{6}
}

func (x *RetryPolicy) GetOnFailure() bool {
	if x != nil {
		return x.OnFailure
	}
	return false
}

func (x *RetryPolicy) GetMaxAttempts() uint32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

type ServiceAccount struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the Kubernetes ServiceAccount.
	// auto-generated as build-bot if not specified.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Name of the Kubernetes Secret containing registry credentials.
	// Sourced from the environment SecretStore via ExternalSecret.
	// Must be of type kubernetes.io/dockerconfigjson.
	Secret        string `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceAccount) Reset() {
	*x = ServiceAccount{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAccount) ProtoMessage() {}

func (x *ServiceAccount) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAccount.ProtoReflect.Descriptor instead.
func (*ServiceAccount) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceAccount) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceAccount) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

type Param struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parameter name — must match a param declared in the BuildStrategy.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Parameter value — overrides strategy defaults.
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Param) Reset() {
	*x = Param{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Param) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Param) ProtoMessage() {}

func (x *Param) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Param.ProtoReflect.Descriptor instead.
func (*Param) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{8}
}

func (x *Param) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Param) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type BuildStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current lifecycle phase. Set by the controller.
	Phase *v1.BuildStatusPhase `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	// Fully qualified image reference including digest, once pushed.
	// e.g. docker.io/nkanyezisolutions/for-kaniko-app@sha256:abc...
	Image string `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	// Name of the Shipwright BuildRun that last executed this Build.
	// Use this to fetch full build logs and step details.
	ExecutionRef string `protobuf:"bytes,3,opt,name=execution_ref,json=executionRef,proto3" json:"execution_ref,omitempty"`
	// Human-readable status message. Populated on failure.
	Message string `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	// When the most recent BuildRun started.
	StartTime *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	// When the most recent BuildRun completed (success or failure).
	CompletionTime *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=completion_time,json=completionTime,proto3" json:"completion_time,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BuildStatus) Reset() {
	*x = BuildStatus{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildStatus) ProtoMessage() {}

func (x *BuildStatus) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildStatus.ProtoReflect.Descriptor instead.
func (*BuildStatus) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{9}
}

func (x *BuildStatus) GetPhase() *v1.BuildStatusPhase {
	if x != nil {
		return x.Phase
	}
	return nil
}

func (x *BuildStatus) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *BuildStatus) GetExecutionRef() string {
	if x != nil {
		return x.ExecutionRef
	}
	return ""
}

func (x *BuildStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BuildStatus) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *BuildStatus) GetCompletionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletionTime
	}
	return nil
}

// CreateBuild — declare a new Build intent.
// Controller emits a Shipwright Build on reconciliation.
type CreateBuildRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Desired spec for the new Build.
	Spec          *BuildSpec `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBuildRequest) Reset() {
	*x = CreateBuildRequest{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuildRequest) ProtoMessage() {}

func (x *CreateBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBuildRequest.ProtoReflect.Descriptor instead.
func (*CreateBuildRequest) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{10}
}

func (x *CreateBuildRequest) GetSpec() *BuildSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type CreateBuildResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The created Build including generated metadata and initial status.
	Build         *Build `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBuildResponse) Reset() {
	*x = CreateBuildResponse{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBuildResponse) ProtoMessage() {}

func (x *CreateBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBuildResponse.ProtoReflect.Descriptor instead.
func (*CreateBuildResponse) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{11}
}

func (x *CreateBuildResponse) GetBuild() *Build {
	if x != nil {
		return x.Build
	}
	return nil
}

// GetBuild — fetch a Build by name.
type GetBuildRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the Build CR to fetch.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildRequest) Reset() {
	*x = GetBuildRequest{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildRequest) ProtoMessage() {}

func (x *GetBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildRequest.ProtoReflect.Descriptor instead.
func (*GetBuildRequest) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{12}
}

func (x *GetBuildRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetBuildResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Build         *Build                 `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildResponse) Reset() {
	*x = GetBuildResponse{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildResponse) ProtoMessage() {}

func (x *GetBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildResponse.ProtoReflect.Descriptor instead.
func (*GetBuildResponse) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{13}
}

func (x *GetBuildResponse) GetBuild() *Build {
	if x != nil {
		return x.Build
	}
	return nil
}

// UpdateBuild — full replace of the Build spec.
// Equivalent to kubectl apply — all fields replaced.
type UpdateBuildRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Full Build object including metadata and desired spec.
	Build         *Build `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBuildRequest) Reset() {
	*x = UpdateBuildRequest{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBuildRequest) ProtoMessage() {}

func (x *UpdateBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBuildRequest.ProtoReflect.Descriptor instead.
func (*UpdateBuildRequest) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateBuildRequest) GetBuild() *Build {
	if x != nil {
		return x.Build
	}
	return nil
}

type UpdateBuildResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The updated Build as observed by the controller.
	Build         *Build `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBuildResponse) Reset() {
	*x = UpdateBuildResponse{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBuildResponse) ProtoMessage() {}

func (x *UpdateBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBuildResponse.ProtoReflect.Descriptor instead.
func (*UpdateBuildResponse) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateBuildResponse) GetBuild() *Build {
	if x != nil {
		return x.Build
	}
	return nil
}

// PatchBuild — partial update using JSON merge patch RFC 7396.
// Only specified fields are updated — others left unchanged.
type PatchBuildRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the Build CR to patch.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// JSON merge patch document — RFC 7396.
	// e.g. {"spec":{"policy":{"retry":{"max_attempts":5}}}}
	Patch         string `protobuf:"bytes,2,opt,name=patch,proto3" json:"patch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchBuildRequest) Reset() {
	*x = PatchBuildRequest{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchBuildRequest) ProtoMessage() {}

func (x *PatchBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchBuildRequest.ProtoReflect.Descriptor instead.
func (*PatchBuildRequest) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{16}
}

func (x *PatchBuildRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PatchBuildRequest) GetPatch() string {
	if x != nil {
		return x.Patch
	}
	return ""
}

type PatchBuildResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The patched Build as observed by the controller.
	Build         *Build `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PatchBuildResponse) Reset() {
	*x = PatchBuildResponse{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PatchBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PatchBuildResponse) ProtoMessage() {}

func (x *PatchBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PatchBuildResponse.ProtoReflect.Descriptor instead.
func (*PatchBuildResponse) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{17}
}

func (x *PatchBuildResponse) GetBuild() *Build {
	if x != nil {
		return x.Build
	}
	return nil
}

// ListBuilds — list Build CRs with optional filtering and paging.
type ListBuildsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter by current lifecycle phase.
	Phase *v1.BuildStatusPhase `protobuf:"bytes,1,opt,name=phase,proto3,oneof" json:"phase,omitempty"`
	// Filter by strategy name.
	// e.g. kaniko | buildah-shipwright-managed-push | buildpacks-v3
	Strategy *string `protobuf:"bytes,2,opt,name=strategy,proto3,oneof" json:"strategy,omitempty"`
	// Maximum number of results to return. Server may return fewer.
	PageSize *int32 `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3,oneof" json:"page_size,omitempty"`
	// Token from a previous ListBuildsResponse.next_page_token.
	// Omit for the first request.
	PageToken     *string `protobuf:"bytes,4,opt,name=page_token,json=pageToken,proto3,oneof" json:"page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBuildsRequest) Reset() {
	*x = ListBuildsRequest{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBuildsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBuildsRequest) ProtoMessage() {}

func (x *ListBuildsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBuildsRequest.ProtoReflect.Descriptor instead.
func (*ListBuildsRequest) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{18}
}

func (x *ListBuildsRequest) GetPhase() *v1.BuildStatusPhase {
	if x != nil {
		return x.Phase
	}
	return nil
}

func (x *ListBuildsRequest) GetStrategy() string {
	if x != nil && x.Strategy != nil {
		return *x.Strategy
	}
	return ""
}

func (x *ListBuildsRequest) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ListBuildsRequest) GetPageToken() string {
	if x != nil && x.PageToken != nil {
		return *x.PageToken
	}
	return ""
}

type ListBuildsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The list of Build CRs matching the request filters.
	Builds []*Build `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
	// Token to retrieve the next page. Empty if no more results.
	NextPageToken *string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3,oneof" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBuildsResponse) Reset() {
	*x = ListBuildsResponse{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBuildsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBuildsResponse) ProtoMessage() {}

func (x *ListBuildsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBuildsResponse.ProtoReflect.Descriptor instead.
func (*ListBuildsResponse) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{19}
}

func (x *ListBuildsResponse) GetBuilds() []*Build {
	if x != nil {
		return x.Builds
	}
	return nil
}

func (x *ListBuildsResponse) GetNextPageToken() string {
	if x != nil && x.NextPageToken != nil {
		return *x.NextPageToken
	}
	return ""
}

// DeleteBuild — delete a Build CR.
// The controller garbage-collects the Shipwright Build and all BuildRuns.
type DeleteBuildRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the Build CR to delete.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBuildRequest) Reset() {
	*x = DeleteBuildRequest{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuildRequest) ProtoMessage() {}

func (x *DeleteBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBuildRequest.ProtoReflect.Descriptor instead.
func (*DeleteBuildRequest) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteBuildRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteBuildResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the Build was successfully deleted.
	Success       bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBuildResponse) Reset() {
	*x = DeleteBuildResponse{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBuildResponse) ProtoMessage() {}

func (x *DeleteBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBuildResponse.ProtoReflect.Descriptor instead.
func (*DeleteBuildResponse) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteBuildResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// TriggerBuild — fire a BuildRun against an existing Build CR.
// Build-specific RPC — no equivalent in OrganizationService.
// Useful for manual reruns or CI webhook dispatch.
type TriggerBuildRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the Build CR to trigger a run against.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Per-run param overrides. Applied on top of spec.params.
	// Useful for SHA overrides on manual triggers.
	Params        []*Param `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerBuildRequest) Reset() {
	*x = TriggerBuildRequest{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerBuildRequest) ProtoMessage() {}

func (x *TriggerBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerBuildRequest.ProtoReflect.Descriptor instead.
func (*TriggerBuildRequest) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{22}
}

func (x *TriggerBuildRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TriggerBuildRequest) GetParams() []*Param {
	if x != nil {
		return x.Params
	}
	return nil
}

type TriggerBuildResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the emitted Shipwright BuildRun.
	// Use GetBuild or WatchBuild to track progress.
	ExecutionRef string `protobuf:"bytes,1,opt,name=execution_ref,json=executionRef,proto3" json:"execution_ref,omitempty"`
	// The Build CR after the trigger was applied.
	Build         *Build `protobuf:"bytes,2,opt,name=build,proto3" json:"build,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerBuildResponse) Reset() {
	*x = TriggerBuildResponse{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerBuildResponse) ProtoMessage() {}

func (x *TriggerBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerBuildResponse.ProtoReflect.Descriptor instead.
func (*TriggerBuildResponse) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{23}
}

func (x *TriggerBuildResponse) GetExecutionRef() string {
	if x != nil {
		return x.ExecutionRef
	}
	return ""
}

func (x *TriggerBuildResponse) GetBuild() *Build {
	if x != nil {
		return x.Build
	}
	return nil
}

// WatchBuild — stream phase transitions for a Build CR.
// Delivers an event for every controller reconciliation loop.
type WatchBuildRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the Build CR to watch.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchBuildRequest) Reset() {
	*x = WatchBuildRequest{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchBuildRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchBuildRequest) ProtoMessage() {}

func (x *WatchBuildRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchBuildRequest.ProtoReflect.Descriptor instead.
func (*WatchBuildRequest) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{24}
}

func (x *WatchBuildRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type WatchBuildResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Current state of the Build at this point in the stream.
	Build *Build `protobuf:"bytes,1,opt,name=build,proto3" json:"build,omitempty"`
	// The type of change that triggered this event.
	Type          v1.EventType `protobuf:"varint,2,opt,name=type,proto3,enum=blanketops.common.v1.EventType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchBuildResponse) Reset() {
	*x = WatchBuildResponse{}
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchBuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchBuildResponse) ProtoMessage() {}

func (x *WatchBuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blanketops_environments_v1beta1_build_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchBuildResponse.ProtoReflect.Descriptor instead.
func (*WatchBuildResponse) Descriptor() ([]byte, []int) {
	return file_blanketops_environments_v1beta1_build_proto_rawDescGZIP(), []int{25}
}

func (x *WatchBuildResponse) GetBuild() *Build {
	if x != nil {
		return x.Build
	}
	return nil
}

func (x *WatchBuildResponse) GetType() v1.EventType {
	if x != nil {
		return x.Type
	}
	return v1.EventType(0)
}

var File_blanketops_environments_v1beta1_build_proto protoreflect.FileDescriptor

const file_blanketops_environments_v1beta1_build_proto_rawDesc = "" +
	"\n" +
	"+blanketops/environments/v1beta1/build.proto\x12\x1fblanketops.environments.v1beta1\x1a blanketops/common/v1/build.proto\x1a'blanketops/common/v1/buildtrigger.proto\x1a blanketops/common/v1/event.proto\x1a#blanketops/common/v1/metadata.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc9\x01\n" +
	"\x05Build\x12:\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1e.blanketops.common.v1.MetadataR\bmetadata\x12>\n" +
	"\x04spec\x18\x02 \x01(\v2*.blanketops.environments.v1beta1.BuildSpecR\x04spec\x12D\n" +
	"\x06status\x18\x03 \x01(\v2,.blanketops.environments.v1beta1.BuildStatusR\x06status\"\x83\x04\n" +
	"\tBuildSpec\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12J\n" +
	"\bstrategy\x18\x02 \x01(\v2..blanketops.environments.v1beta1.BuildStrategyR\bstrategy\x12B\n" +
	"\x06source\x18\x03 \x01(\v2*.blanketops.environments.v1beta1.GitSourceR\x06source\x12D\n" +
	"\x06policy\x18\x04 \x01(\v2,.blanketops.environments.v1beta1.BuildPolicyR\x06policy\x12X\n" +
	"\x0fservice_account\x18\x05 \x01(\v2/.blanketops.environments.v1beta1.ServiceAccountR\x0eserviceAccount\x12>\n" +
	"\x06params\x18\x06 \x03(\v2&.blanketops.environments.v1beta1.ParamR\x06params\x123\n" +
	"\atimeout\x18\a \x01(\v2\x19.google.protobuf.DurationR\atimeout\x12;\n" +
	"\ftime_to_live\x18\b \x01(\v2\x19.google.protobuf.DurationR\n" +
	"timeToLive\"\xb2\x01\n" +
	"\tGitSource\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1a\n" +
	"\brevision\x18\x02 \x01(\tR\brevision\x12\x1f\n" +
	"\vcontext_dir\x18\x03 \x01(\tR\n" +
	"contextDir\x12\x14\n" +
	"\x05depth\x18\x04 \x01(\rR\x05depth\x12\x1d\n" +
	"\n" +
	"ssl_verify\x18\x05 \x01(\bR\tsslVerify\x12!\n" +
	"\fclone_secret\x18\x06 \x01(\tR\vcloneSecret\"`\n" +
	"\rBuildStrategy\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\x04kind\x18\x02 \x01(\v2'.blanketops.common.v1.BuildStrategyKindR\x04kind\"\xb1\x01\n" +
	"\vBuildPolicy\x12^\n" +
	"\x10allowed_triggers\x18\x01 \x03(\v23.blanketops.environments.v1beta1.BuildTriggerPolicyR\x0fallowedTriggers\x12B\n" +
	"\x05retry\x18\x02 \x01(\v2,.blanketops.environments.v1beta1.RetryPolicyR\x05retry\"P\n" +
	"\x12BuildTriggerPolicy\x12:\n" +
	"\x04type\x18\x01 \x01(\v2&.blanketops.common.v1.BuildTriggerTypeR\x04type\"O\n" +
	"\vRetryPolicy\x12\x1d\n" +
	"\n" +
	"on_failure\x18\x01 \x01(\bR\tonFailure\x12!\n" +
	"\fmax_attempts\x18\x02 \x01(\rR\vmaxAttempts\"<\n" +
	"\x0eServiceAccount\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\"1\n" +
	"\x05Param\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xa0\x02\n" +
	"\vBuildStatus\x12<\n" +
	"\x05phase\x18\x01 \x01(\v2&.blanketops.common.v1.BuildStatusPhaseR\x05phase\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12#\n" +
	"\rexecution_ref\x18\x03 \x01(\tR\fexecutionRef\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x129\n" +
	"\n" +
	"start_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartTime\x12C\n" +
	"\x0fcompletion_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\x0ecompletionTime\"T\n" +
	"\x12CreateBuildRequest\x12>\n" +
	"\x04spec\x18\x01 \x01(\v2*.blanketops.environments.v1beta1.BuildSpecR\x04spec\"S\n" +
	"\x13CreateBuildResponse\x12<\n" +
	"\x05build\x18\x01 \x01(\v2&.blanketops.environments.v1beta1.BuildR\x05build\"%\n" +
	"\x0fGetBuildRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"P\n" +
	"\x10GetBuildResponse\x12<\n" +
	"\x05build\x18\x01 \x01(\v2&.blanketops.environments.v1beta1.BuildR\x05build\"R\n" +
	"\x12UpdateBuildRequest\x12<\n" +
	"\x05build\x18\x01 \x01(\v2&.blanketops.environments.v1beta1.BuildR\x05build\"S\n" +
	"\x13UpdateBuildResponse\x12<\n" +
	"\x05build\x18\x01 \x01(\v2&.blanketops.environments.v1beta1.BuildR\x05build\"=\n" +
	"\x11PatchBuildRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05patch\x18\x02 \x01(\tR\x05patch\"R\n" +
	"\x12PatchBuildResponse\x12<\n" +
	"\x05build\x18\x01 \x01(\v2&.blanketops.environments.v1beta1.BuildR\x05build\"\xf1\x01\n" +
	"\x11ListBuildsRequest\x12A\n" +
	"\x05phase\x18\x01 \x01(\v2&.blanketops.common.v1.BuildStatusPhaseH\x00R\x05phase\x88\x01\x01\x12\x1f\n" +
	"\bstrategy\x18\x02 \x01(\tH\x01R\bstrategy\x88\x01\x01\x12 \n" +
	"\tpage_size\x18\x03 \x01(\x05H\x02R\bpageSize\x88\x01\x01\x12\"\n" +
	"\n" +
	"page_token\x18\x04 \x01(\tH\x03R\tpageToken\x88\x01\x01B\b\n" +
	"\x06_phaseB\v\n" +
	"\t_strategyB\f\n" +
	"\n" +
	"_page_sizeB\r\n" +
	"\v_page_token\"\x95\x01\n" +
	"\x12ListBuildsResponse\x12>\n" +
	"\x06builds\x18\x01 \x03(\v2&.blanketops.environments.v1beta1.BuildR\x06builds\x12+\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tH\x00R\rnextPageToken\x88\x01\x01B\x12\n" +
	"\x10_next_page_token\"(\n" +
	"\x12DeleteBuildRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"/\n" +
	"\x13DeleteBuildResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"i\n" +
	"\x13TriggerBuildRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12>\n" +
	"\x06params\x18\x02 \x03(\v2&.blanketops.environments.v1beta1.ParamR\x06params\"y\n" +
	"\x14TriggerBuildResponse\x12#\n" +
	"\rexecution_ref\x18\x01 \x01(\tR\fexecutionRef\x12<\n" +
	"\x05build\x18\x02 \x01(\v2&.blanketops.environments.v1beta1.BuildR\x05build\"'\n" +
	"\x11WatchBuildRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x87\x01\n" +
	"\x12WatchBuildResponse\x12<\n" +
	"\x05build\x18\x01 \x01(\v2&.blanketops.environments.v1beta1.BuildR\x05build\x123\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1f.blanketops.common.v1.EventTypeR\x04type2\xd1\a\n" +
	"\fBuildService\x12x\n" +
	"\vCreateBuild\x123.blanketops.environments.v1beta1.CreateBuildRequest\x1a4.blanketops.environments.v1beta1.CreateBuildResponse\x12o\n" +
	"\bGetBuild\x120.blanketops.environments.v1beta1.GetBuildRequest\x1a1.blanketops.environments.v1beta1.GetBuildResponse\x12x\n" +
	"\vUpdateBuild\x123.blanketops.environments.v1beta1.UpdateBuildRequest\x1a4.blanketops.environments.v1beta1.UpdateBuildResponse\x12u\n" +
	"\n" +
	"PatchBuild\x122.blanketops.environments.v1beta1.PatchBuildRequest\x1a3.blanketops.environments.v1beta1.PatchBuildResponse\x12u\n" +
	"\n" +
	"ListBuilds\x122.blanketops.environments.v1beta1.ListBuildsRequest\x1a3.blanketops.environments.v1beta1.ListBuildsResponse\x12x\n" +
	"\vDeleteBuild\x123.blanketops.environments.v1beta1.DeleteBuildRequest\x1a4.blanketops.environments.v1beta1.DeleteBuildResponse\x12{\n" +
	"\fTriggerBuild\x124.blanketops.environments.v1beta1.TriggerBuildRequest\x1a5.blanketops.environments.v1beta1.TriggerBuildResponse\x12w\n" +
	"\n" +
	"WatchBuild\x122.blanketops.environments.v1beta1.WatchBuildRequest\x1a3.blanketops.environments.v1beta1.WatchBuildResponse0\x01B\xb0\x01\n" +
	"\x1fv1beta1.blanketops.environmentsB\n" +
	"BuildProtoZ_github.com/ntlaletsi70/blanketops-environments-contract/blanketops/environments/v1beta1;v1beta1\xaa\x02\x1fBlanketOps.Environments.V1Beta1b\x06proto3"

var (
	file_blanketops_environments_v1beta1_build_proto_rawDescOnce sync.Once
	file_blanketops_environments_v1beta1_build_proto_rawDescData []byte
)

func file_blanketops_environments_v1beta1_build_proto_rawDescGZIP() []byte {
	file_blanketops_environments_v1beta1_build_proto_rawDescOnce.Do(func() {
		file_blanketops_environments_v1beta1_build_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_blanketops_environments_v1beta1_build_proto_rawDesc), len(file_blanketops_environments_v1beta1_build_proto_rawDesc)))
	})
	return file_blanketops_environments_v1beta1_build_proto_rawDescData
}

var file_blanketops_environments_v1beta1_build_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_blanketops_environments_v1beta1_build_proto_goTypes = []any{
	(*Build)(nil),                 // 0: blanketops.environments.v1beta1.Build
	(*BuildSpec)(nil),             // 1: blanketops.environments.v1beta1.BuildSpec
	(*GitSource)(nil),             // 2: blanketops.environments.v1beta1.GitSource
	(*BuildStrategy)(nil),         // 3: blanketops.environments.v1beta1.BuildStrategy
	(*BuildPolicy)(nil),           // 4: blanketops.environments.v1beta1.BuildPolicy
	(*BuildTriggerPolicy)(nil),    // 5: blanketops.environments.v1beta1.BuildTriggerPolicy
	(*RetryPolicy)(nil),           // 6: blanketops.environments.v1beta1.RetryPolicy
	(*ServiceAccount)(nil),        // 7: blanketops.environments.v1beta1.ServiceAccount
	(*Param)(nil),                 // 8: blanketops.environments.v1beta1.Param
	(*BuildStatus)(nil),           // 9: blanketops.environments.v1beta1.BuildStatus
	(*CreateBuildRequest)(nil),    // 10: blanketops.environments.v1beta1.CreateBuildRequest
	(*CreateBuildResponse)(nil),   // 11: blanketops.environments.v1beta1.CreateBuildResponse
	(*GetBuildRequest)(nil),       // 12: blanketops.environments.v1beta1.GetBuildRequest
	(*GetBuildResponse)(nil),      // 13: blanketops.environments.v1beta1.GetBuildResponse
	(*UpdateBuildRequest)(nil),    // 14: blanketops.environments.v1beta1.UpdateBuildRequest
	(*UpdateBuildResponse)(nil),   // 15: blanketops.environments.v1beta1.UpdateBuildResponse
	(*PatchBuildRequest)(nil),     // 16: blanketops.environments.v1beta1.PatchBuildRequest
	(*PatchBuildResponse)(nil),    // 17: blanketops.environments.v1beta1.PatchBuildResponse
	(*ListBuildsRequest)(nil),     // 18: blanketops.environments.v1beta1.ListBuildsRequest
	(*ListBuildsResponse)(nil),    // 19: blanketops.environments.v1beta1.ListBuildsResponse
	(*DeleteBuildRequest)(nil),    // 20: blanketops.environments.v1beta1.DeleteBuildRequest
	(*DeleteBuildResponse)(nil),   // 21: blanketops.environments.v1beta1.DeleteBuildResponse
	(*TriggerBuildRequest)(nil),   // 22: blanketops.environments.v1beta1.TriggerBuildRequest
	(*TriggerBuildResponse)(nil),  // 23: blanketops.environments.v1beta1.TriggerBuildResponse
	(*WatchBuildRequest)(nil),     // 24: blanketops.environments.v1beta1.WatchBuildRequest
	(*WatchBuildResponse)(nil),    // 25: blanketops.environments.v1beta1.WatchBuildResponse
	(*v1.Metadata)(nil),           // 26: blanketops.common.v1.Metadata
	(*durationpb.Duration)(nil),   // 27: google.protobuf.Duration
	(*v1.BuildStrategyKind)(nil),  // 28: blanketops.common.v1.BuildStrategyKind
	(*v1.BuildTriggerType)(nil),   // 29: blanketops.common.v1.BuildTriggerType
	(*v1.BuildStatusPhase)(nil),   // 30: blanketops.common.v1.BuildStatusPhase
	(*timestamppb.Timestamp)(nil), // 31: google.protobuf.Timestamp
	(v1.EventType)(0),             // 32: blanketops.common.v1.EventType
}
var file_blanketops_environments_v1beta1_build_proto_depIdxs = []int32{
	26, // 0: blanketops.environments.v1beta1.Build.metadata:type_name -> blanketops.common.v1.Metadata
	1,  // 1: blanketops.environments.v1beta1.Build.spec:type_name -> blanketops.environments.v1beta1.BuildSpec
	9,  // 2: blanketops.environments.v1beta1.Build.status:type_name -> blanketops.environments.v1beta1.BuildStatus
	3,  // 3: blanketops.environments.v1beta1.BuildSpec.strategy:type_name -> blanketops.environments.v1beta1.BuildStrategy
	2,  // 4: blanketops.environments.v1beta1.BuildSpec.source:type_name -> blanketops.environments.v1beta1.GitSource
	4,  // 5: blanketops.environments.v1beta1.BuildSpec.policy:type_name -> blanketops.environments.v1beta1.BuildPolicy
	7,  // 6: blanketops.environments.v1beta1.BuildSpec.service_account:type_name -> blanketops.environments.v1beta1.ServiceAccount
	8,  // 7: blanketops.environments.v1beta1.BuildSpec.params:type_name -> blanketops.environments.v1beta1.Param
	27, // 8: blanketops.environments.v1beta1.BuildSpec.timeout:type_name -> google.protobuf.Duration
	27, // 9: blanketops.environments.v1beta1.BuildSpec.time_to_live:type_name -> google.protobuf.Duration
	28, // 10: blanketops.environments.v1beta1.BuildStrategy.kind:type_name -> blanketops.common.v1.BuildStrategyKind
	5,  // 11: blanketops.environments.v1beta1.BuildPolicy.allowed_triggers:type_name -> blanketops.environments.v1beta1.BuildTriggerPolicy
	6,  // 12: blanketops.environments.v1beta1.BuildPolicy.retry:type_name -> blanketops.environments.v1beta1.RetryPolicy
	29, // 13: blanketops.environments.v1beta1.BuildTriggerPolicy.type:type_name -> blanketops.common.v1.BuildTriggerType
	30, // 14: blanketops.environments.v1beta1.BuildStatus.phase:type_name -> blanketops.common.v1.BuildStatusPhase
	31, // 15: blanketops.environments.v1beta1.BuildStatus.start_time:type_name -> google.protobuf.Timestamp
	31, // 16: blanketops.environments.v1beta1.BuildStatus.completion_time:type_name -> google.protobuf.Timestamp
	1,  // 17: blanketops.environments.v1beta1.CreateBuildRequest.spec:type_name -> blanketops.environments.v1beta1.BuildSpec
	0,  // 18: blanketops.environments.v1beta1.CreateBuildResponse.build:type_name -> blanketops.environments.v1beta1.Build
	0,  // 19: blanketops.environments.v1beta1.GetBuildResponse.build:type_name -> blanketops.environments.v1beta1.Build
	0,  // 20: blanketops.environments.v1beta1.UpdateBuildRequest.build:type_name -> blanketops.environments.v1beta1.Build
	0,  // 21: blanketops.environments.v1beta1.UpdateBuildResponse.build:type_name -> blanketops.environments.v1beta1.Build
	0,  // 22: blanketops.environments.v1beta1.PatchBuildResponse.build:type_name -> blanketops.environments.v1beta1.Build
	30, // 23: blanketops.environments.v1beta1.ListBuildsRequest.phase:type_name -> blanketops.common.v1.BuildStatusPhase
	0,  // 24: blanketops.environments.v1beta1.ListBuildsResponse.builds:type_name -> blanketops.environments.v1beta1.Build
	8,  // 25: blanketops.environments.v1beta1.TriggerBuildRequest.params:type_name -> blanketops.environments.v1beta1.Param
	0,  // 26: blanketops.environments.v1beta1.TriggerBuildResponse.build:type_name -> blanketops.environments.v1beta1.Build
	0,  // 27: blanketops.environments.v1beta1.WatchBuildResponse.build:type_name -> blanketops.environments.v1beta1.Build
	32, // 28: blanketops.environments.v1beta1.WatchBuildResponse.type:type_name -> blanketops.common.v1.EventType
	10, // 29: blanketops.environments.v1beta1.BuildService.CreateBuild:input_type -> blanketops.environments.v1beta1.CreateBuildRequest
	12, // 30: blanketops.environments.v1beta1.BuildService.GetBuild:input_type -> blanketops.environments.v1beta1.GetBuildRequest
	14, // 31: blanketops.environments.v1beta1.BuildService.UpdateBuild:input_type -> blanketops.environments.v1beta1.UpdateBuildRequest
	16, // 32: blanketops.environments.v1beta1.BuildService.PatchBuild:input_type -> blanketops.environments.v1beta1.PatchBuildRequest
	18, // 33: blanketops.environments.v1beta1.BuildService.ListBuilds:input_type -> blanketops.environments.v1beta1.ListBuildsRequest
	20, // 34: blanketops.environments.v1beta1.BuildService.DeleteBuild:input_type -> blanketops.environments.v1beta1.DeleteBuildRequest
	22, // 35: blanketops.environments.v1beta1.BuildService.TriggerBuild:input_type -> blanketops.environments.v1beta1.TriggerBuildRequest
	24, // 36: blanketops.environments.v1beta1.BuildService.WatchBuild:input_type -> blanketops.environments.v1beta1.WatchBuildRequest
	11, // 37: blanketops.environments.v1beta1.BuildService.CreateBuild:output_type -> blanketops.environments.v1beta1.CreateBuildResponse
	13, // 38: blanketops.environments.v1beta1.BuildService.GetBuild:output_type -> blanketops.environments.v1beta1.GetBuildResponse
	15, // 39: blanketops.environments.v1beta1.BuildService.UpdateBuild:output_type -> blanketops.environments.v1beta1.UpdateBuildResponse
	17, // 40: blanketops.environments.v1beta1.BuildService.PatchBuild:output_type -> blanketops.environments.v1beta1.PatchBuildResponse
	19, // 41: blanketops.environments.v1beta1.BuildService.ListBuilds:output_type -> blanketops.environments.v1beta1.ListBuildsResponse
	21, // 42: blanketops.environments.v1beta1.BuildService.DeleteBuild:output_type -> blanketops.environments.v1beta1.DeleteBuildResponse
	23, // 43: blanketops.environments.v1beta1.BuildService.TriggerBuild:output_type -> blanketops.environments.v1beta1.TriggerBuildResponse
	25, // 44: blanketops.environments.v1beta1.BuildService.WatchBuild:output_type -> blanketops.environments.v1beta1.WatchBuildResponse
	37, // [37:45] is the sub-list for method output_type
	29, // [29:37] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_blanketops_environments_v1beta1_build_proto_init() }
func file_blanketops_environments_v1beta1_build_proto_init() {
	if File_blanketops_environments_v1beta1_build_proto != nil {
		return
	}
	file_blanketops_environments_v1beta1_build_proto_msgTypes[18].OneofWrappers = []any{}
	file_blanketops_environments_v1beta1_build_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_blanketops_environments_v1beta1_build_proto_rawDesc), len(file_blanketops_environments_v1beta1_build_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_blanketops_environments_v1beta1_build_proto_goTypes,
		DependencyIndexes: file_blanketops_environments_v1beta1_build_proto_depIdxs,
		MessageInfos:      file_blanketops_environments_v1beta1_build_proto_msgTypes,
	}.Build()
	File_blanketops_environments_v1beta1_build_proto = out.File
	file_blanketops_environments_v1beta1_build_proto_goTypes = nil
	file_blanketops_environments_v1beta1_build_proto_depIdxs = nil
}
